vanilla/addons

plugins/Signatures/class.signatures.plugin.php

Fixes bug where signatures could have more signatures than allowed if no spaces were between the multiple image tags.

Signatures plugin: Fix regex for matching bbcode image tags.

---

plugins/GooglePlus/class.googleplus.plugin.php

Google+ will always return an avatar even if the user hasn't selected one which makes Vanilla's default avatar plugins break.
This feature allows forum admins to opt-out of google+ avatars.

Add a config setting to allow forums to not use google+ avatars.

---

plugins/Quotes/class.quotes.plugin.php

Default Markdown doesn't like text against its quotes.

Quotes: add break after Markdown quotes

---

plugins/Signatures/class.signatures.plugin.php

Fixes bug where advanced editor dropdowns were not working in signature form. 
The advanced editor js script adds supplementary js scripts based on the form's format attribute. This ensures that the signatures form has a non-empty, not null format attribute.

Signatures plugin: Explicitly set form format.

---

plugins/QnA/class.qna.plugin.php
plugins/Redirector/class.redirector.plugin.php

These updates are meant to be used with the latest "Legacy Slug" updates to ForumMerge.  When a forum is merged in with these updates, you specify a slug as a kind of namespace for the old incoming forum identifiers.  This slug is then specified as the value for the legacy URL parameter.
Redirector checks to see if legacy is set in the URL.  If it is, it checks to see if ForeignID exists in the table (this column is new to Category and Comment, added by ForumMerge).  If both of those checkout, it concatenates the current forum record (category, comment or discussion) identifier with the legacy slug and searches for a row in the target table with that ForeignID.  The first match that is found is returned as the target record.
Also included is a small fix for multiple p parameters being …

Redirector: Add legacy redirects, fix for multiple URL parameters named p

---

plugins/FileUpload/class.fileupload.plugin.php

* Revert #182's forking of the SaveAs event.
* Add new ImageType arg instead for logic.
* Fix thumbnails malfunctioning on cloud (probably unrelated, but noticed now)

Fix FileUpload's event firing & cloud thumbnails

---

plugins/Redirector/class.redirector.plugin.php

"Friendly URLs" were added in vB4.  Example: /showthread.php?001-demo-thread/page5
PHP interprets these as named parameters with no value.  We need to extract the record ID and potentially a page number from that parameter name.  For the example, we need to extract 001 as a discussion ID and 5 as the page number.  That is accomplished with this feature.

Adding vB4 "Friendly URL" Handling to Redirector Plug-in

---

plugins/ForumMerge/class.forummerge.plugin.php
plugins/ForumMerge/views/merge.php

Adds a legacy slug to incoming forums, which is used in the Redirector plug-in
Added check to comment table to verify rows do not exceed a threshold before attempting to apply changes in structure.  If the threshold is exceeded, the SQL for necessary updates is output for the user to run manually.  If the intended structural updates exist, the exceeded threshold check will not cease the plugin's initialization.

Adding legacy forum slug to ForumMerge

---

plugins/Pockets/class.pockets.plugin.php
plugins/Pockets/library/class.pocket.php
plugins/Pockets/pockets.js
plugins/Pockets/views/addedit.php
plugins/Pockets/views/index.php

This PR adds functionality to hide pockets that are marked as 'ads' for any user with the Garden.AdFree.Allow permission.
Add 'Custom' pocket location
Add permission setting (Garden.AdFree.Allow) 
Add 'Ad' type to pockets
Validate Smarty-rendered pockets with 'Custom' locations (using CanRender function)
Use javascript to hide Repeat options when 'Custom' location is set.

Pockets: Add 'Ad Free' functionality

---

plugins/QnA/class.qna.plugin.php

Also:
Add index to structure.
Add separate method to get unanswered count.
Fixes bug where unanswered pager gets count from discussions.
Relies on https://github.com/vanilla/vanilla/pull/2565

QnA: Get count of unanswered discussions to add to pager.

---

plugins/Signatures/class.signatures.plugin.php

Fixes bug where Warnings2 jailed users still have signatures.

Signatures: Uncomment event.

---

plugins/TouchIcon/class.touchicon.plugin.php
plugins/TouchIcon/views/touchicon.php

Fixes Touch Icons not being able to be uploaded on cloud with CDN.

Let TouchIcon use updated paths

---

plugins/SteamConnect/class.steam.plugin.php

Users' Vanilla usernames were being reset to their current username on Steam every time they authenticated with Steam.  This fix checks to see if the user already has an established Steam ID connection and avoids resetting their Vanilla username if found.
Fixes #210

SteamConnect: Don't set username on existing users

---

plugins/Multilingual/class.multilingual.plugin.php
plugins/Multilingual/modules/class.localechoosermodule.php

This update is in support of the locale PR [here](https://github.com/vanilla/vanilla/pull/2586).
- Improve the locale listing functionality.
- Include the default locale in a less hacky way.
- Use ext-intl for locale names where possible.

Update the mulitlingual plugin to work with locale canonicalization

---

standards/Vanilla/Sniffs/Classes/ValidClassNameSniff.php
standards/Vanilla/Sniffs/Commenting/FunctionCommentSniff.php
standards/Vanilla/Sniffs/Methods/CamelCapsMethodNameSniff.php
standards/Vanilla/ruleset.xml

Allow magic methods and don’t require an underscore on method names.

Fix method naming code standards

---

standards/Vanilla/ruleset.xml

Listen 120 characters is great and all but just shut up about it, CodeSniffer.

Allow lines to go to 150 characters before puking errors

---

plugins/AgeGate/class.agegate.plugin.php
plugins/AgeGate/js/agegate.js

Adds a hidden config setting (Plugins.AgeGate.MinimumAgeWithConsent) that allows a user between the MinimumAgeWithConsent and the MinimumAge to register after confirming they have received consent to register. If this config setting is set, no user under the MinimumAge will be able to register.
Also changes the form field to use 'DateOfBirth' and uses Gdn_Form's date function to render the DateOfBirth field.
Also casening.

AgeGate MinAgeWithConsent config setting

---

plugins/IPBFormatter/class.ipbformatter.plugin.php

Previously, IPB Formatter would not transform URLs into links.  This PR applies Gdn_Format::links to IPBFormatterPlugin::format to fix that.
IPB has a mix of markup and BBCode quote tags.  This PR also translates the markup (blockquote, specifically) quotes into BBCode-style quotes.

Adds linkifying of text links and translation of markup quotes to IPB Formatter

---

plugins/IPBFormatter/class.ipbformatter.plugin.php

Adds handlers for new Advanced Editor events that allow dynamic addition of support for new format slugs.
Relies on https://github.com/vanilla/vanilla/pull/2887

IPB Formatter: Hook into Advanced Editor to add format support

---

plugins/IPBFormatter/class.ipbformatter.plugin.php

Attachments were previously always displayed as images when using IPBFormatter.  This update takes the updated logic from NBBC and applies it to DoAttachment in IPBFormatter to only display as an image when ImageWidth is present as an attribute for the Media record.

Render attachment as anchor in IPBFormatter if ImageWidth not present

---

plugins/NBBC/class.nbbc.plugin.php

Prevents size, table, tr and td BBCode tags from displaying when using NBBC.  The content of the tags is not affected.

Hide some unsupported BBCode tags with NBBC

---

plugins/IPBFormatter/class.ipbformatter.plugin.php

FileUpload was necessary for displaying attachments with IPB Formatter.  However, Advanced Editor has its own attachment handling.  Simultaneously running Advanced Editor and FileUpload leads to a duplicate display of attachments at the bottom of posts.  This update attempts to avoid that duplication by removing that dependency and instead queries the Media table, using the basic method originally used in FileUpload.

Remove FileUpload dependence for attachments in IPB Formatter

---

plugins/QnA/class.qna.plugin.php

Currently everyone can change a discussion to a question and vice versa

Add permission check to DiscussionOptions

---

plugins/jsconnect/class.jsconnect.plugin.php

The URL was incorrect for communities in a subdirectory.

Fix the URL redirect after deleting a jsconnect connection

---

plugins/Whispers/js/whispers.js

The multicomplete on the Whispers form doesn't need livequery as it is not dynamically created or updated.

Whispers: Remove livequery

---

plugins/MeAction/class.meaction.plugin.php
plugins/MeAction/design/meaction.css
plugins/MeAction/js/meaction.js

- This plugin works just fine without the JS and CSS file. Apparently
this was rolled into the core formatter at some point.
- Updated the remaining code to match new coding standards.

MeAction: Remove all assets

---

plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/js/jsconnect.js

Remove the livequery call and just initialize the `.JsConnect-Container` on document.ready.
I couldn't find a place where the `.JsConnect-Container` div could be added dynamically (see `JsConnectPlugin::connectButton()`).
This call has been in the plugin since the beginning, so it was most likely just defensive programming.

jsConnect: Remove livequery call

---

plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/views/settings_addedit.php

* Build up the add/edit form programmatically with Gdn_Form->simple().
* Throw an event so that plugins can add controls to the form.
* Add JsConnectPlugin->addControl() so that plugins can more easily add controls.
* Standardize the saving of jsConnect connections to use proper form saving.

Enhance jsconnect’s add/edit functionality

---

plugins/Spoilers/js/spoilers.js

Blocked by https://github.com/vanilla/vanilla/pull/3041
Once the PreviewLoaded event works, the timeout is not needed anymore.

Spoilers: Remove timeout

---

plugins/jsconnect/views/settings.php
plugins/jsconnect/views/settings_addedit.php

The links in the dashboard settings page for JsConnect were going to outdated pages in the docs that redirected you to more generic help section.

Update links to help docs in jsconnect.

---

plugins/Spoilers/class.spoilers.plugin.php
plugins/Spoilers/js/spoilers.js

Previously the Hide and Show labels for spoilers didn't translate when you were in a different locale.  Now you can set translations for them by setting them in the themehooks file for the theme.

Show spoiler label translations

---

plugins/QnA/views/answers.php

QnA creates a span element with an ID of "latest" just before the accepted comment markup.  This causes a conflict with Vanilla's "latest" element, generally shown farther down the page.  A user visiting a #latest URL for a QnA thread with an accepted answer would always be pulled to the accepted answer comment, instead of the latest comment in the thread.
This fix renames the ID of the QnA pre-accepted-answer element from latest to accepted.

Stop QnA accepted answer from hijacking #latest

---

plugins/QnA/class.qna.plugin.php

The QnA plug-in was sending notifications to users whenever their questions had any kind of response, regardless of their notification preferences.  This update attempts to apply the `DiscussionComment` preferences to any attempted notifications.

Don't force notifications for QnA responses

---

plugins/Ignore/class.ignore.plugin.php

The Ignore plug-in was not updating `CountUnreadConversations` after ignoring a user.  This was causing incorrect inbox counts.
This update adds a call to `ConversationModel::countUnread` at the end of the ignore routine to update `CountUnreadConversations` for the current user.

Update CountUnreadConversations after ignore

---

plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/views/settings.php

Previously, jsConnect would take some of the standard user fields and set them to an empty string if not provided. This would have the side-effect of generating field required errors on subsequent signins which isn’t correct. What should happen is a user should be prompted for the missing field on first sign in and then have subsequent signins work.
To see the effect of this bug:
1. Create a fake jsConnect source with a username, but no email address.
2. SSO with that connection.
3. Change the username in the database or wherever.
4. Sign out and then SSO again.
5. Before the username will not be updated because there will be a hidden error about a missing email address. After this PR the username should update.
As with all SSO PRs this could have regression bugs, but I’m hoping it only …

Fix the way jsConnect handles missing values

---

plugins/Multilingual/class.multilingual.plugin.php
plugins/Multilingual/modules/class.localechoosermodule.php

Some versions of Locale::getDisplayName() return suboptimal choices so it’s necessary to selectively override them.

Allow display name overrides in the multilingual plugin

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php

Make sure the discussions array is okay before looping through it.

Fix warning in Civil Tongue

---

plugins/NBBC/class.nbbc.plugin.php

This update changes the way spoiler content markup is generated from spoiler tags.  The simplified wrapper is compatible with the spoiler style rules in the Advanced Editor plug-in's [wysiwyg.css](https://github.com/vanilla/vanilla/blob/7b2d94a8a17646947106f107c836edb31567d7d1/plugins/editor/design/wysiwyg.css#L218).

Update NBBC spoiler markup

---

plugins/FileUpload/class.fileupload.plugin.php

Fire an event to allow uploaded images to be manipulated after a discussion has been saved.

Add hook to watermark images after saving discussion.

---

plugins/Pockets/class.pockets.plugin.php

Currently, using the "Repeat Every" or "Given Indexes" option with Location "Between Discussions" does not work when `Vanilla.Layout.Discussions` is set to `table`. This is because the wrapper is set to `<li>` for those elements by default. This pull request makes Pockets aware of `Vanilla.Layout.Discussions` and uses a full-width table row instead.

Pockets: enable repeat on discussion table view

---

plugins/RoleTitle/class.roletitle.plugin.php

In two function some values were being called from an array but the indexes were in the wrong letter casing so they were returning nothing.

RoleTitle Plugin: Fix case of array indexes.

---

plugins/IPBFormatter/class.ipbformatter.plugin.php

Disable HTML encoding in IPB formatting plug-in.  Requires https://github.com/vanilla/vanilla/pull/3642

Don't encode HTML in IPB NBBC

---

plugins/NBBC/class.nbbc.plugin.php

Using http prevents the video from being rendered on https sites.
Also, youtube do not let you use http anymore so I didn't bother using the current site protocol.

Switch over to https for youtube links.

---

plugins/Pockets/library/class.pocket.php

If a pocket is set to repeat with a "Begin At" value, it is not currently respecting that value.  This seems to be due to some bad logic.
This update revises the logic for when to begin a pocket's repetition, making it respect the "Begin At" value.

Fix repetition logic for "Begin At" in Pockets

---

plugins/QnA/class.qna.plugin.php

Fix the number of points awarded from the QnA plugin when the Reaction plugin is also enabled.

Points per accepted answer give the wrong value.

---

plugins/QnA/class.qna.plugin.php

I'm currently working on a plug-in to integrate Vanilla with Algolia search and I'd like to include QnA accepted answers as a flag in Algolia to improve a comments ranking. For this I need to know when a comment is marked as accepted. This change adds a `AfterAccepted` event which passes the activity array as an event argument.
It might be possible to use the `BeforeSave` event from `ActivityModel`, but the `ActivityModel` has a check to make sure that users are notified of changes they make to their own data. that means the `BeforeSave` event doesn't get triggered bending on who marks the thread as accepted. This event resolves this.
I've signed the CLA should you wish to pull this in :-)

QnA: Add `AfterAccepted` event

---

plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/views/settings.php

"Sign in popups" and "Autoconnect" are two core settings of Vanilla that have an impact on jsConnect's functionality, but locating them in the dashboard may not be intuitive.  This update adds these two configuration options to a new "Settings" area on the primary jsConnect configuration page.
Closes https://github.com/vanilla/vanilla/issues/3083
Closes https://github.com/vanilla/vanilla/issues/3084

Add auto-connect and sign-in popup settings to jsConnect

---

plugins/QnA/class.qna.plugin.php

Create a hook for the optional adjusting of the number of questions displayed in the QnA plugin based on, for example, the current sub community in the cloud hosted environment.
This will fix the issue https://github.com/vanilla/multisite/issues/28
A handler was added to the subcommunities plugin to handle this event in PR https://github.com/vanilla/multisite/pull/29/

Add event to correct for question count based on sub communities.

---

plugins/FileUpload/class.fileupload.plugin.php

`Gdn_Upload::copyLocal ` is not a static function and should not be called in a static context.
This update replaces the `copyLocal` call with one made to an instance of `Gdn_UploadImage`.
Closes #337

Fix invalid call to Gdn_Upload::copyLocal

---

plugins/SteamConnect/class.steamconnect.plugin.php

Plugin SteamConnect has a mixture of "Steam" and "SteamConnect" in folder name, file name, plugin info and class name.

Correct SteamConnect class and file name

---

plugins/QnA/class.qna.plugin.php

When I enabled the UseBigButtons options I was initially really confused as to why the New Discussion button was still a dropdown. It seems redundant to have two different buttons for "Ask a question" on the page, so I've added a _not_ condition to the addition of asking a question if `UseBigButtons` is enabled.

QnA: Don't display "Ask a question" in the drop down if BigButtons is enabled

---

plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/functions.jsconnect.php

The `client_id` property should be plain text so don't let it mis-render in error messages.

Escape clientid in jsConnect errors

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php

This update adds the`PCRE_UTF8` flag to pattern matching in the CivilTongueEx plug-in.  Prior to this update, Cyrillic characters were not properly recognized and offending words containing them were not censored.
Closes #338

Fix Cyrillic character recognition in CivilTongueEx

---

plugins/ForumMerge/class.forummerge.plugin.php

This was happening when UpdateUserID is `NULL` and multiple users have oldID set to `NULL` too.

Fix "subquery returns more than 1 row" in ForumMerge plugin.

---

plugins/Redirector/class.redirector.plugin.php

Fix https://github.com/vanilla/vanilla/issues/2383 in conjunction with https://github.com/vanilla/porter/pull/128
In short, if p is supplied but not T we fallback to a discussion using the ForeignID field.

Redirect vBulletin showthread.php?p={POSTID} properly.

---

plugins/TrollManagement/class.trollmanagement.plugin.php

Reindex the array so that json_encode does not treat the array as an object due the the index being non sequencial
Fix https://github.com/vanilla/vanilla/issues/4310

Fix discussion array indexation after troll posts are removed from it.

---

plugins/welcomepost/class.welcomepost.plugin.php

Redirect to the welcomepost page after email confirmation if enabled.

Take Garden.Registration.ConfirmEmail into account in the WelcomePost plugin

---

plugins/Pockets/views/index.php
plugins/jsconnect/views/settings.php

Allowing the table layout to choose the column widths resulted in some unpleasant-looking tables. Recent updates to the dashboard css allow us to hint at a column width. The column will never shrink below the specified width. This, combined with jquery.tablejengo.js give us perfectly responsive tables without squishing or trying to push the table beyond the width of its container.

Make tables render better according to their content

---

plugins/QnA/class.qna.plugin.php

- Move the `questionCount` hook so that it works when caching is enabled.
- Show unanswered questions from groups. 
- *The group category has the `HideAllDiscussions` flag set to true. This means that the category won't be returned by `CategoryModel::categoryWatch();`. To circumvent that we explicitly set all categories on the discussion controller. That way we will get the unanswered questions from everywhere.*
- Add a hook to allow the categories from previous point to be modified. Needed by Subcommunities for example.

Fix Q&A interactions with other plugins

---

plugins/CssThemes/class.cssthemes.plugin.php
plugins/FeedDiscussions/class.feeddiscussions.plugin.php
plugins/Liked/class.liked.plugin.php
plugins/MathJax/class.mathjax.plugin.php
plugins/Pockets/class.pockets.plugin.php
plugins/PostCount/class.postcount.plugin.php
plugins/RightToLeft/class.righttoleft.plugin.php
plugins/Signatures/class.signatures.plugin.php
plugins/Voting/class.voting.plugin.php
plugins/jsconnect/class.jsconnect.plugin.php

Fixes a bunch of notices and issues where nav items don't appear in the panel. We've started using call_user_func in the plugin manager https://github.com/vanilla/vanilla/commit/b9f91ee66b8e54f63239f291b42b9172dfb800a3, which doesn't allow references.

Don't pass sender by reference

---

plugins/LocaleDeveloper/class.developerlocale.php
plugins/LocaleDeveloper/class.localedeveloper.plugin.php

Fixes an issue where translations were not captured when the translation functions used a different casing. Also includes formatting changes (use w=1 to review).

Fix case sensitivity of translation function names in the locale developer

---

plugins/ShareThis/class.sharethis.plugin.php
plugins/ShareThis/design/ShareThis.css

On several themes, the buttons are cut off. The plugin assumes box-sizing is set to "content-box". I explicitly gave content-box sizing to the plugin to avoid issues.
Closes #403

Share This - Fix for button heights

---

plugins/Akismet/class.akismet.plugin.php

TypePad no longer is a viable Akismet key provider, so if you haven't set that option by now, you should never set it. This hides it (and fixes the option spelling in it, derp) if it's blank. Also provides nicer functionality specifics in the addon description.

Deprecate TypePad from Akismet and improve plugin description

---

plugins/CivilTongueEx/views/index.php
plugins/CustomizeText/views/customizetext.php
plugins/Disqus/views/settings.php
plugins/FeedDiscussions/views/feeddiscussions.php
plugins/Pockets/views/addedit.php
plugins/Pockets/views/index.php
plugins/QnA/views/configuration.php
plugins/ShareThis/views/sharethis.php
plugins/Spoof/views/spoof.php
plugins/TouchIcon/views/touchicon.php
plugins/jsconnect/views/settings.php
plugins/jsconnect/views/settings_addedit.php

Does three things:
1. Uses new helpAsset() function to add info to the help asset and render it properly
2. Removes the wrapper for form footer and adds it to the form class instead.
3. Uses data-title, data-body, data-css-class, etc. for modal content overriding instead of passing data-modal-content as an object.
Help Asset styling and modal overrides rely on https://github.com/vanilla/vanilla/pull/4631
Help Asset rendering relies on https://github.com/vanilla/vanilla/pull/4632

Update Settings Views

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php

Depends on https://github.com/vanilla/internal/pull/737
Fixes https://github.com/vanilla/addons/issues/408
Fix filtering on the categories view.
Filter out groups and events fields.
P.S. Yeah I know it is a 2 in one.. don't crucify me.

Update CivilTongueEx to work on Groups and Events + bugfix on categories

---

plugins/Ignore/class.ignore.plugin.php

When ignoring a user, the Ignore plug-in currently [checks the ignore permissions of the target user](https://github.com/vanilla/addons/blob/30546963e6f7f1d9e3bcf72606f386cf930bdbe8/plugins/Ignore/class.ignore.plugin.php#L400), not the current user.  If you're attempting to unignore a user who has had their ignore permissions revoked, you're met with a "You can't ignore that person" error.  You can *ignore* those kinds of users, because when setting up a new ignore, `IgnorePlugin::ignoreRestricted` overwrites the value being checked with a result verifying the target user isn't an administrator or something.  When you're *unignoring* a user, the value is being set to `true` and matches the first case in the switch statement that follows.
This update removes the `$UserID` parameter being …

Fix failure to unignore user if their ignore privileges have been revoked

---

plugins/jsconnect/views/settings.php

This update adds a warning message to the jsConnect area of the dashboard when a provider is in test mode.
Closes #385

Add warning to jsConnect dashboard when providers in test mode

---

plugins/TrollManagement/class.trollmanagement.plugin.php

If there were no trolls, the option to mark an user as one would never appear.

[Troll] Fix the toggle option not being avalaible in the profile when there are no trolls

---

plugins/welcomepost/class.welcomepost.plugin.php
plugins/welcomepost/js/welcomepost.js

This PR makes changes to the Welcome Post plugin, which sends new users to /post/discussion prompting them to introduce themselves to the community:
Removes the messaging from a javascript modal and em
- beds it in the page
- Changes the title of the page
- Instead of Cancel it says Skip (since the user has been redirected there while en route to another page)
- Supports users who have just created accounts via SSO

Change the functionality of the Welcome Post plugin

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php

Fix retrieving of discussions in Civil Tongue hook to allow for replacements.
Closes https://github.com/vanilla/addons/issues/442

Censor discussion titles in /discussions

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/structure.php

Fix https://github.com/vanilla/addons/issues/428
Check the UserPoint table.
If Reaction is OFF the only source should be QnA.
If Reaction is ON there should be both QnA (for first answer on a question) and Reaction (for accepted answer).
Using the QnAOptions tool should remove/add points properly.

Fix Q&A point-awarding interactions with Reactions

---

plugins/welcomepost/class.welcomepost.plugin.php

The Welcome Post gives the user the option to not post a "Welcome" post by clicking cancel which would send you to the default controller. This could have some unwanted consequences. This PR sends the user to / and assumes routing will make sure the user is going to the default page.

Link to root of forum when opting out of Welcome Post

---

plugins/Pockets/class.pockets.plugin.php
plugins/Pockets/library/class.pocket.php
plugins/Pockets/views/addedit.php
plugins/Pockets/views/index.php

This update will require a utility/update for the Test Mode enabling to work properly.
* Refactor the test mode out of the Disabled field in the Pockets table
* Add a TestMode column to the Pockets table
* Add a toggle to enable/disable a pocket from the Pockets index
* Add enable and disable endpoints to the plugin
Relies on https://github.com/vanilla/vanilla/pull/5216 for styling tweaks
Closes https://github.com/vanilla/vanilla/issues/5098

Update Pockets plugin enable/disable state

---

plugins/Redirector/class.redirector.plugin.php

Modified behaviour of redirector plugin for the vBulletin case"showthread.php?=p".
First the plugin will try to match the URL to a comment. If no comment is returned, the plugin will try to match if to a discussion using the foreign ID column.
Fixes https://github.com/vanilla/addons/issues/460

Fix redirector plugin for vBulletin case showthread.php?=p

---

plugins/Sitemaps/class.sitemaps.plugin.php
plugins/Sitemaps/views/settings.php

This plugin didn't work properly with plugins that changed the url structure of Vanilla. I've added an event that allows to filter the categories sent to the plugin.

Sitemap Plugin - Added event to filter categories

---

plugins/Disqus/class.disqus.plugin.php
plugins/Disqus/views/settings.php

Fixes https://github.com/vanilla/addons/issues/468
The callback URL must now match exactly what is configured and the Application.
Since the callback is a mandatory field it is now useless to provide it.

Remove redirect_uri form Disqus

---

plugins/Participated/class.participated.plugin.php

This update attempts to optimize how a user's "participated" discussions are queried. The UserDiscussion table is queried based on the value of the `Participated` field and the Discussion table is joined in.
The methods of joining in additional user and category data seemed outdated, so I've updated them to match what's currently used in `DiscussionModel::getWhere`.
Closes #462

Optimize discussion polling in Participated plug-in

---

plugins/Signatures/class.signatures.plugin.php

One of the `t()` tags was missing and another was incorrect. Both of these already exist in vanilla/locales.

Fix signature plugin translate tags

---

plugins/QnA/class.qna.plugin.php

Fixes https://github.com/vanilla/addons/issues/496
Question (post) requiring approval would get set to "Answered" upon approval.

Fixing when question with no comments would get set to Answered

---

plugins/Participated/class.participated.plugin.php

https://github.com/vanilla/addons/pull/477 attempted to optimize the querying of a user's participated discussions, but it also removed some fields that were necessary for calculating new post counts on the /discussions/participated page.
This update re-adds the necessary fields from the `UserDiscussion` table as part of the discussion query and restores proper rendering of counts on the aforementioned page.
Closes #490 
Backport to [release/2017-Q2-2](https://github.com/vanilla/addons/tree/release/2017-Q2-2)

Fix new post count not being displayed on Participated Discussions page

---

plugins/Signatures/class.signatures.plugin.php

Fix multiple issues introduced by https://github.com/vanilla/addons/pull/480.
Signature max height and max length will not be properly parsed.

Properly validate integers in Signature plugin

---

plugins/RoleTitle/class.roletitle.plugin.php

https://github.com/vanilla/addons/pull/491 broke the addon info array for the Role Titles plug-in. This update removes the broken array.

Fix broken add-on info array in Role Titles plug-in

---

plugins/Signatures/class.signatures.plugin.php

There were two strings in the Signature plugin that gave the same message. One had a period, the other not. When translated the one with the period remained in English.

Fix translation of error message for images in signatures.

---

plugins/QnA/class.qna.plugin.php

Asker was receiving an answer notification with a link to the question when a user replied to his question.
Answerer was receiving a notification saying his answer was accepted but with no link to the question. This PR adds this link to the notification.
Fixes https://github.com/vanilla/addons/issues/449

Adding question link to accepted answer notification

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php

Hooked into "beforeSave" to filter out activity messages in Civil Tongue plugin.
Closes https://github.com/vanilla/addons/issues/467

Civil Tongue: Add filtering to activity & notifications

---

plugins/Participated/addon.json
plugins/Participated/class.participated.plugin.php

#477 updated the Participated Discussions addon to use the `UserDiscussion` table for pulling its data. However, to maintain identical functionality, joining in records from the `Comment` table was necessary. This additional join negates a lot of the performance gains possible from switching over to `UserDiscussion`, especially for prolific commenters.
This update alters the functionality of Participated Discussions in a fundamental way: every discussion a user has *participated* in will be displayed. This means discussions the user has created will now be included in this list, in addition to discussions the user has commented on. Current functionality has the list only pulling the latter.
I've also altered the addon description to reflect the functionality change and incremented its …

Improve load time of Participated Discussions

---

plugins/QnA/structure.php

Q&A's structure routine has a block dedicated to [adding or updating an "Accepted Answer" reaction](https://github.com/vanilla/addons/blob/3a41a3c7510fd3237050f893c9a5e8cb6abbd9fd/plugins/QnA/structure.php#L160), if the Reactions is enabled. The problem is it uses a truthy/falsy condition, based on the result of `Gdn_Model::getWhere`. This function returns a `Gdn_Dataset` object, so the result will always be truthy. Because of this, the "Accepted Answer" reaction is always attempting to be updated. If it doesn't exist, a fatal SQL error is thrown and the Q&A addon cannot be enabled.
This update calls `resultArray` on the `Gdn_Dataset` result from `Gdn_Model::getWhere`. If no results are found, an empty array is returned. This is a valid falsy value, so the condition functions as intended.

Fix inability to setup QnA for the first time alongside Reactions

---

plugins/Signatures/class.signatures.plugin.php

There is a stray "Default" field in the Signatures settings form. This is due to the form's configuration having the Signatures.Images.MaxNumber field's "Default" attribute defined outside of its array.
This update does a couple things:
1. Moves the "Default" attribute for Signatures.Images.MaxNumber into its config array, thus removing the field from the form.
1. Formats the form configuration array to be more readable.

Fix phantom "Default" field in Signature settings

---

plugins/Pockets/class.pockets.plugin.php

A notice was being thrown by this callback function `PocketsPlugin::pocketStringCb()` because it was being called outside of `preg_replace_callback()`. This PR:
- deprecates `pocketStringCb` function which should never have been marked as public
- moves the function into a lambda
- removes the extra call the callback
This should make it into 2.5 so I've added a task to delete the deprecated function in 2.6 - #530

[Pockets] Fix undefined offset notice in Pockets

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php

Vanilla's [`EventManager` uses `call_user_func_array`](https://github.com/vanilla/vanilla/blob/27e57016f48c964782df35a5e1b13f1e528b5ebe/library/Garden/EventManager.php#L278) to invoke event hooks. The Civil Tongue addon's `activityModel_beforeSave` function signature attempts to pass its `$args` parameter by reference, which is not compatible with the aforementioned call to [`call_user_func_array`](http://php.net/manual/en/function.call-user-func-array.php). The hook fails and is not executed.
This update drops the attempt to pass by reference, which causes the hook to be properly fired.

Fix ActivityModel before-save hook in Civil Tongue Ex

---

plugins/Signatures/class.signatures.plugin.php

* Fix docblocks (commit 1).
* Fix `structure()` logic to not be suicidal (commit 2) by checking to make sure the deprecated configs ACTUALLY EXIST before overwriting the good ones. Also, Custom Theme pooped a satan baby into there somehow.

Fix signatures addon wiping its global configs on structure updates

---

plugins/Redirector/class.redirector.plugin.php

Get satisfaction uses slug created from the discussion name to create their URL.
Migrating the URL slug (removing the domain) into the UrlCode column and this code will redirect the discussions properly. 
Example:
https://community.{generic}.com/{generic}/topics/-discussion-fake-software-thread-99-71-0-d5t1siggrtrn

Add a get satisfaction discussion url slug case to the redirector plugin

---

plugins/welcomepost/README.md
plugins/welcomepost/class.welcomepost.plugin.php

Presently the Welcome Post addon only supplies a default title to the welcome post, this PR adds a translation code so that forum admins can add a translation string to pre-fill the welcome post body.

Optionally add a default body to the Welcome Post

---

plugins/Participated/addon.json
plugins/Participated/class.participated.plugin.php

This update backports #535 to [releases/2017-Q2-6](https://github.com/vanilla/addons/tree/release/2017-Q2-6).

Backport: Improve load time of Participated Discussions

---

plugins/QnA/class.qna.plugin.php

Fixes https://github.com/vanilla/addons/issues/551
There is a feature that you can enable that track points per category.
To track the points properly you have to call 
```
$source = ['QnA', 'CategoryID' => $categoryID];
UserModel::givePoints($userID, $points, $source, $timestamp);
```
where `$categoryID` is the "PointsCategoryID" of the category of the post.
Fortunately there is a convenience method on the CategoryModel that does all the work for you!

Fix QnA addon not tracking points per-category

---

plugins/burnerblocker/class.burnerblocker.plugin.php

Attempting to use Burner Blocker currently throws a notice when a user registers and the primary hook is never actually fired.
```
Parameter 2 to BurnerBlockerPlugin::userModel_beforeRegister_handler() expected to be a reference, value given
```
This update alters the hook function's signature to expect a value, not a reference. Since the elements in `$args` are already references, the intended functionality is unaffected.
Closes #566

Fix Burner Blocker not hooking into registrations

---

plugins/HipChat/addon.json
plugins/HipChat/class.hipchat.plugin.php

I'm adding the ability to opt into notifications for all comments in addition to existing always-on notifications for all discussions. Default is false for backwards compatibility.
I've also changed the locales to specify the action being taken. These codes aren't in locales yet anyway, and this isn't in use on cloud outside our staff forum so I don't think that's necessary right now.
Also did a couple minor code cleanups, incremented to 0.4, and updated the addon description.
I plan to backport this since it's only used by us and therefore a safe change.

HipChat: Add comment notifications

---

plugins/jsconnect/class.jsconnect.plugin.php

Fix an infinite redirection bug. safeUrl('') default to the current page.

Make sure that the target is not empty before setting it

---

plugins/example/addon.json

- Add "name" key
- remove "settingsPermission" and "requiredTheme"
Also increased version number and required Vanilla version 2.5. "settingsPermission" was removed based on [that comment](https://open.vanillaforums.com/discussion/comment/243085/#Comment_243085) and the fact that this key isn't used anywhere in Vanilla

Update example addon's addon.json

---

plugins/Participated/class.participated.plugin.php

`DiscussionModel::categoryPermissions()` will query the database if there is no cache.
The plugins was polluting the SQL object before that call.

Fix SQL query pollution in Participated addon

---

plugins/categoryaslink/addon.json
plugins/categoryaslink/class.categoryaslink.plugin.php

Sometimes Admins have want to funnel users who are looking through the categories to another part of the forum or to a specific post. 
This PR creates a feature that will allow admins, when creating or editing a category in the dashboard, to either attach an existing CategoryID or any valid URI that will be used to as the destination whenever a user clicks on or navigates to that category.

Use a category on the categories page as a link to another category or discussion.

---

plugins/QnA/class.qna.plugin.php
plugins/Signatures/class.signatures.plugin.php

Fixes https://github.com/vanilla/addons/issues/560
The problem was that comments were filtered out in Q&A `discussionController_beforeDiscussionRender_handler()` which interfered with the signatures are fetched. To fix this issue the filtering was moved to a later event and the signature fetching was moved to an earlier event!

Fix signature not showing on Q&A answers

---

plugins/QnA/addon.json
plugins/QnA/class.qna.plugin.php

- When a rejected comment is edited it used to mark the question answered. Now editing a comment leaves the Q&A status alone.
- When deleting a comment or doing anything else that causes the comment count to recalculate the full Q&A status is recalculated for the question which should be more robust.
Closes vanilla/support#5

Fix discussion Q&A status for edited and deleted comments

---

plugins/Participated/class.participated.plugin.php

Backport #581
>`DiscussionModel::categoryPermissions()` will query the database if there is no cache.
The plugins was polluting the SQL object before that call.

Backport: Fix SQL query pollution in Participated plugin

---

plugins/necro/class.necro.plugin.php

Apparently we used to allow Linux timestamps in these fields. Now they fatal and stop the discussion from bumping.

Fix necro addon datetime usage

---

plugins/necro/class.necro.plugin.php

Original: https://github.com/vanilla/addons/pull/591
This is causing fatal errors & blocking post bumping. 
Patch is an isolated change.

Backport: Fix necro datetime patch

---

plugins/Redirector/class.redirector.plugin.php

We are currently handling a migration from vBulletin. Site used vBulletin basic friendly URLs.
https://www.vbulletin.com/docs/html/main/options_seofriendly_urls
The current implementation seems to be mishandling the discussion case. We want to recover the discussion ID when the `t=`  parameter is not set or more specifically is not part of the URL.
This new implementation handles it correctly while preventing us from sending us to the discussion when the link is actually a comment.

Fix discussion URLs in vBulletin format not always being detected by Redirector

---

plugins/Redirector/class.redirector.plugin.php

Backport of #593
> We are currently handling a migration from vBulletin. Site used vBulletin basic friendly URLs.
>
>https://www.vbulletin.com/docs/html/main/options_seofriendly_urls
>
>The current implementation seems to be mishandling the discussion case. We want to recover the discussion ID when the `t=`  parameter is not set or more specifically is not part of the URL.
>
>This new implementation handles it correctly while preventing us from sending us to the discussion when the link is actually a comment.

Backport: Fix discussion URLs in vBulletin format not always being detected by Redirector

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/tests/APIv2/CommentsAnswerTest.php
plugins/QnA/tests/APIv2/DiscussionsQuestionTest.php
plugins/QnA/tests/APIv2/QnaTestHelperTrait.php

Fixes https://github.com/vanilla/internal/issues/1166
Depends on https://github.com/vanilla/vanilla/pull/6646, https://github.com/vanilla/vanilla/pull/6635, https://github.com/vanilla/vanilla/pull/6634
- Expose question metadata in discussion attributes field
- Expose answer metadata in comments attributes field
- Add POST /discussions/question to allow to create questions.
- Add PATCH /comments/answer to allow to update answers metadata

Add API capabilities to QnA addon

---

plugins/Pockets/library/class.pocket.php
plugins/Signatures/class.signatures.plugin.php

Reference vanilla/vanilla#6673
Related vanilla/internal#1464
Related vanilla/vanilla#6758
Adds user content class for non-plaintext content created by users. This class is used for some styles related the rich editor.

Add userContent class onto signatures

---

plugins/AuthorSelector/class.authorselector.plugin.php

The link for the ChangeAuthor-link needs to be build with the `url()` function.

Fix AuthorSelector ChangeAuthor-Link

---

plugins/jsconnect/class.jsconnect.plugin.php

Presently when you have to troubleshoot JSConnect there is no logging on the remote server. This PR will use our Logger interface to log data whenever there is a problem while connecting.

Add logging to JSConnect.

---

plugins/jsconnect/class.jsconnect.plugin.php

Back port PR #608 
> Presently when you have to troubleshoot JSConnect there is no logging on the remote server. This PR will use our Logger interface to log data whenever there is a problem while connecting.

Backport: Add logging to JSConnect.

---

plugins/HipChat/class.hipchat.plugin.php

Currently HipChat is reporting comments as being from the discussion author (OP) rather than the actual comment author. This grabs the comment data so we can derive the true author. The hook data around this is super brittle so I decided to get it from the database directly.

Fix HipChat comment author data

---

plugins/AuthorSelector/class.authorselector.plugin.php

Fixes https://github.com/vanilla/addons/issues/615
Bug was introduced by https://github.com/vanilla/addons/pull/605
The result of `url()` is sent to `anchor()` which calls `url()` again if the link is not absolute. This causes problems in certain cases. ie Subcommunities.

Fix double url() call

---

plugins/QnA/class.qna.plugin.php

Fixes https://github.com/vanilla/addons/issues/616
So the problem was that, when restored from the logs, the question was automatically marked as answered even if there was no comments. I updated the whole thing to rely on `recalculateDiscussionQnA()`.
I also fixed `recalculateDiscussionQnA()` which has `answered` and `unanswered` inverted.

Fix recalculateDiscussionQnA logic and use it where relevant

---

plugins/jsconnect/class.jsconnect.plugin.php

We recently added logging to JSConnect but we mis-named one log entry and we missed the most important one: Signature error. 
This PR will a log where there is a signature error and renames the generic error that comes back from the authenticating server.

More improvements in logging to JSConnect.

---

plugins/jsconnect/class.jsconnect.plugin.php

Backport #623 
> We recently added logging to JSConnect but we mis-named one log entry and we missed the most important one: Signature error.
> This PR will a log where there is a signature error and renames the generic error that comes back from the authenticating server.

Backport: More improvements in logging to JSConnect.

---

plugins/jsconnect/class.jsconnect.plugin.php

We recently added logging to JSConnect to allow us to debug.  We record the data that is used to generate a signature when the signature fails but we don't record the signature itself for comparison.
We strip out certain elements from the passed JSData array including the signatures and the version.  In this PR we log the JSData before and after it has had these elements stripped out.
Also in this PR, we will log JSData that has passed all validation so that we can know what a successful log in looks like.

Add the signature to error logs when logging a signature error in JSConnect.

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/tests/APIv2/CommentsAnswerTest.php

By fixing `recalculateDiscussionQnA()` in this [PR](https://github.com/vanilla/addons/pull/620/files#diff-b96a190297fb9e48f8391f75e7da42d3R564) we ended up finding that the discussion record doesn't contains the updated counts on it which makes `recalculateDiscussionQnA()` not assigning the proper `QnA` value in certain cases.

Add the up-to-date discussion's counts to the question record before recalculating it

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/tests/APIv2/CommentsAnswerTest.php

Backport #620 and #627 which fixed https://github.com/vanilla/addons/issues/616

[Backport] Fix recalculateDiscussionQnA logic and use it where relevant

---

plugins/categoryaslink/README.md
plugins/categoryaslink/addon.json
plugins/categoryaslink/class.categoryaslink.plugin.php

This PR fixes the fact that the Category as Link plugin doesn't work when subcommunities are turned on by doing two things:
1. Making the Category as Link fire first (changing the priority)
2. Using the Subcommunities way of constructing the URL if Subcommunities are turned on.

Fix the Category as Link Addon so it works with Subcommunities.

---

plugins/categoryaslink/README.md
plugins/categoryaslink/addon.json
plugins/categoryaslink/class.categoryaslink.plugin.php

Backport PR #639 
This PR fixes the fact that the Category as Link plugin doesn't work when subcommunities are turned on by doing two things:
Making the Category as Link fire first (changing the priority)
Using the Subcommunities way of constructing the URL if Subcommunities are turned on.

Backport: Fix the Category as Link Addon so it works with Subcommunities.

---

plugins/QnA/class.qna.plugin.php

Closes https://github.com/vanilla/addons/issues/643.
Refactored the `recalculateDiscussionQnA()` function based on the logic established in https://github.com/vanilla/addons/issues/643.
Also, removed the faulty separate logic to set the discussion's QnA state when an answer is treated as helpful or not, now using the refactored `recalculateDiscussionQnA()`. The discussion state is now being set to the correct state regardless of how many answers remain to be treated.

Fix recalculation of discussions QnA state

---

plugins/SteamConnect/README.md
plugins/SteamConnect/class.steamconnect.plugin.php

closes #647 
The error "uniqueID is required" was because we were trying to match `http://steamcommunity.com/.. `with the received` https://steamcommunity.com/.. `
[class.steamconnect.plugin.php#L125](https://github.com/vanilla/addons/blob/master/plugins/SteamConnect/class.steamconnect.plugin.php#L125 )

Fix broken SSO in Steam Connect

---

plugins/jsconnect/addon.json

License GNU GPL2 added to upload the plugin to opensource.

jsconnect: added GNU GPL2 license

---

plugins/QnA/tests/APIv2/CommentsAnswerTest.php
plugins/QnA/tests/APIv2/DiscussionsQuestionTest.php

This test that after a question has an rejected answer then another answer is posted that the question's status will be **answered**.  An additional test to verify that the status of a posted question 
is **unanswered**.  Tests to validate the date accepted and date answered fields were also added
Closed #646

Add test to cover questions after an answer has been rejected

---

plugins/QnA/class.qna.plugin.php

closes [#652](https://github.com/vanilla/addons/issues/652)
When a discussion is changed to type Question, accepting an answer results in an external link warning.
- Change any discussion type to QnA
- Accept an answer

Qna: Accepting answer results in external link warning

---

plugins/QnA/class.qna.plugin.php

Closes [#3](https://github.com/vanilla/support/issues/3)
**What Changed**
I added notification preferences for QnA when:
- A question is answered 
- An answer is accepted

User option to disable/enable QnA notifications

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/models/class.qnamodel.php

The goal here was to add an option to recalculate the current QnA state of all questions through the `dba/counts` endpoint.
Relevant information on the PR
---
* Recalculation happens in batches of 1000 questions at a time to prevent locking the table for too long.
* There is no "capping" on how many questions you can update. (Should we add one?)
* I tried optimizing queries as much as possible, as an example 100,000 questions with 200,000 answers take about 2 minutes to fully update on my local.
* On the UI you can see a "progress" in percentage to preventing feeling like the job is stuck.
* You can refer to the `recalculateDiscussionsQnA()` method to see the logic I used to update the records.

Add question states recalculation to dba/counts

---

plugins/QnA/models/class.qnamodel.php

Add a check to the alter table threshold config setting on the Discussion.QnA recalculation. Simply a database safety measure.

Add threshold to QnA recalculation through dba/counts

---

plugins/QnA/class.qna.plugin.php

closes [#667](https://github.com/vanilla/addons/issues/667)
Details in the referenced issue.
- Run utility/update.
- Register a new user.
- New user should have notifications enabled by default.

QnA: add functionality to have notifications enabled by default

---

plugins/QnA/class.qna.plugin.php

closes [#113](https://github.com/vanilla/support/issues/113)
This PR remove the notification message when a question is answered.

QnA: remove notification message after a question is answered

---

plugins/jsconnect/class.jsconnect.plugin.php

Add cache options to SQL driver to cache getProviders query response for 15 min.
That allows app to avoid unnecessary DB connection to be initialized in some cases.
I've discussed this patch with @DaazKu. 
His opinion - we should provide wider solution with some global scope but not only apply to jsconnect plugin.
Fixes: https://github.com/vanilla/vanilla-patches/issues/387

Add cache options to SQL driver to cache getProviders query response 

---

plugins/QnA/class.qna.plugin.php

This allows roles with the Garden.Curation.Manage permission or higher to accept answers for questions that they didn't ask.  Previously it was only roles with Garden.Moderation.Manage.
AcceptAnswer is a reactiontype that uses this permission.  User can react with this permission.
https://github.com/vanilla/internal/blob/2297d4283299b990d0f9190cabe4af2102fea962/plugins/Reactions/class.reactionmodel.php#L928
To Test:
1. Create a role Garden.Curation.Manage permission.
2. Apply this role to a user (usera)
3. Create a question another user. (userb)
4. With another user answer the question. (userc)
5. Verify that you receive the "Did this answer the question?" span attached to answer. (usera)
6. Verify that accepting answer works.
_Backwards Compatibility_
7. Repeat steps with a user with …

QnA: Change permission to AcceptAnswer to Garden.Curation.Manage

---

plugins/jsconnect/class.jsconnect.plugin.php

This PR will close #691 
Remove the type declaration for the parameter being passed to the getProviderSqlCacheKey() method in JSConnect.
To recreate:
1) Turn on the JSConnect plugin.
2) Create a JSConnect Connection.
3) For Client ID choose a string.
4) Save.
5) Try to edit it, you will get a fatal error.
To test: 
1) Check out this branch.
2) Recreate the steps above.
3) You should get an edit screen.

Fix JSConnect to allow for strings as AuthenticationKeys.

---

plugins/Redirector/class.redirector.plugin.php

A customer that came from Lithium has been reporting some issues with the Redirector plugin. The problem is that discussions with `/ta-p/` and `/m-p/` are hitting 404's.
After looking at the plugin, I saw that we never implemented redirections for discussions with `/ta-p/` so URLs like the one below weren't redirecting. (It's currently redirecting because I created a temporary route)
https://community.rapidminer.com/t5/RapidMiner-Studio-Knowledge-Base/Real-Time-Financial-Data-via-Alpha-Venture-API-alternative-to/ta-p/41119
To fix that, I added the following condition to the `t5Filter` function.
```php
} elseif (val('_arg2', $get) == 'ta-p') {
$result = [
'_arg3' => 'DiscussionID',
];
}
```
It will now get the message id from the URL and try to match the discussion with the same id in …

Redirector: Improve Lithium's 301 redirects

---

plugins/QnA/class.qna.plugin.php

Following https://github.com/vanilla/vanilla/pull/7960 the global `touchConfig` method is deprecated.
PR replacing usages in core: https://github.com/vanilla/vanilla/pull/8203
This PR updates `touchConfig` usage to be `Gdn::config()->touch()` instead.

Replace deprecated touchConfig usage

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/tests/APIv2/DiscussionsQuestionTest.php

This update adds including accepted answers as part of the "question" attributes on a discussion. By default, only the comment IDs of accepted answers come down. However, users may use "acceptedAnswers" in the "expand" parameter of a call to /api/v2/discussions/{id}, which will return the body of those comments, as well.
Closes #676

Add expanding QnA answers in discussions API resource

---

plugins/QnA/class.qna.plugin.php

Reverting this pr https://github.com/vanilla/addons-patches/pull/29

Fix Error Posting Questions

---

plugins/InvisibilityCloak/class.invisibilitycloak.plugin.php
plugins/Sitemaps/class.sitemaps.plugin.php

With vanilla/vanilla#8744, core support for robots.txt is added. This support is essentially a migration of the functionality from Sitemaps. Because of that, Sitemaps has been updated to remove the redundant functionality. Additionally, Invisibility Cloak has been refactored to use the new `Robots.Invisible` config, instead of attempting to create its own robots.txt endpoint.
No functional changes should be apparent after this update. Sitemaps and Invisibility Cloak should return the same robots.txt as they did before these changes.
Closes vanilla/vanilla#8576

Update Sitemaps and Invisibility Cloak to use core robots.txt

---

plugins/QnA/class.qna.plugin.php

**Issue**
Currently in questions which have been announced will not display in the discussions::unanswered endpoint. 
**Solution**
In the DiscussionModel::GetWhere method we are removing announcements 
https://github.com/vanilla/vanilla/blob/221d0bd4f4c29e13d71f762528f6c7ecf01f83c0/applications/vanilla/models/class.discussionmodel.php#L754.  
In order to include announcements we can add the condition in the where statement as described 
https://github.com/vanilla/vanilla/blob/221d0bd4f4c29e13d71f762528f6c7ecf01f83c0/applications/vanilla/models/class.discussionmodel.php#L650
**To test**
1. Create a new question. Verify that it shows up in the 'Unanswered' queue.
2. Announce that thread (in Its Category and Recent
3. Discussions). The question will still count against the number in …

Include announced questions in discussions/unanswered

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/views/post.php

related [#426](https://github.com/vanilla/support/issues/426)
When a category has custom permissions that does not allow questions, users can still for post a question in the category by browsing to post/question/no-question-category
When a new question is created, [the QnA addon's postController_question_create hook](https://github.com/vanilla/addons/blob/d483877ea17a8578f891be621a71e15b4783bc16/plugins/QnA/class.qna.plugin.php#L1115) is called that calls [`PostController::discussion`](https://github.com/vanilla/vanilla/blob/4df04723ba501b050951ef1c4afd51d92d072391/applications/vanilla/controllers/class.postcontroller.php#L112). We're not checking the allowed discussion types when creating the discussion. 
In [the QnA addon's postController_question_create …

Fix: category discussion type setting not respected when creating a question

---

plugins/NoIndex/class.noindex.plugin.php

If you are using NoIndex addon and Bump addon, you can't use bump if you enable it after NoIndex because NoIndex plugin has the same attribute

Fix conflict with Bump plugin

---

plugins/QnA/addon.json
plugins/QnA/class.qna.plugin.php

If another addon has augmented the discussion attribute schema then the Q&A addon would wipe that change out. This if statement offers a check for a targeted augmentation.

Fix Q&A APIv2 schema augmentation

---

plugins/categoryaslink/class.categoryaslink.plugin.php

call public method `subcommunityURL`
instead of deprecated static.
Relates to: https://github.com/vanilla/multisite/pull/218

Update 'categoryaslink' plugin according to 'subcommunities' plugin change

---

plugins/NoIndex/addon.json
plugins/NoIndex/class.noindex.plugin.php

There were a few notices on the page because of improper calls to old deprecated methods.

Fix notices in the no index addon

---

plugins/NoIndex/addon.json
plugins/NoIndex/class.noindex.plugin.php

The no index addon was not checking for an authenticated post back which is a narrow CSRF vulnerability. This PR also cleans up the spacing in the method and updates the parameter to the current best practice.
Closes https://github.com/vanilla/vanilla-patches/issues/268.

Authenticate the postback in the no index addon

---

plugins/Sitemaps/addon.json

Since this plugin requires the latest events when we moved Robots.txt into core, I've updated the minimum required version of Vanilla to release an updated version of the addon to OSS.

Require vanilla 3.1 for the latest sitemaps plugin

---

.circleci/config.yml
plugins/QnA/addon.json
plugins/QnA/class.qna.plugin.php
plugins/QnA/models/SearchRecordTypeAnswer.php
plugins/QnA/models/SearchRecordTypeQuestion.php
plugins/QnA/tests/APIv2/QnaTestHelperTrait.php
plugins/QnA/tests/Sphinx/SearchQuestionTest.php

Initialize advanced search record types: `question` and `answer`
Relates to: https://github.com/vanilla/vanilla/issues/9318

Initialize advanced search record types

---

plugins/Bump/class.bump.plugin.php

The `setField` function from the discussion model is a wrapper for `Gdn_Model::setField` which fires the `AfterSetField` event.
By replacing the `setProperty` call by `setField`, it is possible to hook into the AfterSetField event after a discussion is bumped. Both functions are used to update an existing records and produce the same results.

Bump plugin: Use setField instead of setProperty.

---

plugins/QnA/models/SearchRecordTypeAnswer.php
plugins/QnA/models/SearchRecordTypeQuestion.php
plugins/QnA/tests/Sphinx/SearchQuestionTest.php

backporting https://github.com/vanilla/addons/pull/747

Backport: add infrastructure template to SearchRecordType models in QnA plugin (release/2019.014)

---

plugins/OpenID/class.lightopenid.php

This PR would permanently set the cURL option to follow 3xx redirects to false.

Update OpenID curl option to not follow.

---

plugins/CivilTongueEx/addon.json
plugins/CivilTongueEx/class.civiltongueex.plugin.php
plugins/CivilTongueEx/tests/Models/CivilTongueExTest.php

This PR will fix CivilTongue when trying to replace words that use ‘$’ at the beginning or end of a word. (ex. a$$, $hit). The dollar symbol is considered to be a word boundary so when trying to find a word that incorporates '$' as an 'S' at the beginning or end of a string it won't find it.
Also this PR creates a test.
- Turn on the Civil Tongue Plugin
- Add the words 'a$$; $hit' to the filtered words.
- Add text to the site with the 'a$$' and '$hit' in them.
- Check that they have been replaced with the replacement text.

Fix CivilTongue addon not able to find words ending '$'.

---

plugins/OpenID/class.lightopenid.php

Permanently set the cURL option for following 3xx redirects to false.

Backport: Update OpenID curl option to not follow.

---

plugins/Disqus/addon.json

related https://github.com/vanilla/vanilla-patches/issues/642
This PR sets the plugin to hidden as requested in the referenced issue.

Set disqus plugin to hidden

---

plugins/debugbar/class.debugbar.plugin.php

Use `getAssetRoot()` instead of the deprecated `assetRoot()`.

Debugbar: Use Gdn_request::getAssetRoot()

---

plugins/ShareThis/addon.json

The addon is deprecated. I’m hiding it in vfoptions, but also here.

Mark the Share This addon as hidden

---

plugins/QnA/class.qna.plugin.php

There is currently no way to determine if the unanswered count is affecting the Pager when hooking into the `unansweredCount` event.
The $pager parameter has been added to the `getUnansweredCount` function and is passed as an argument to the `unansweredCount` event. False is the default value assigned to this variable.

Add $pager parameter to getUnansweredCount function in Q&A plugin.

---

plugins/Signatures/addon.json
plugins/Signatures/class.signatures.plugin.php

Users can be deleted or banned for having signatures that are offensive or abusive. Hiding their signatures is a sensible tweak.
In the case of deleted users, they can have their data deleted, but not always.
Closes https://github.com/vanilla/support/issues/842

Hide signatures of deleted or banned users

---

plugins/Emotify/addon.json

The first step in deprecation. Also removes the HTML description to fix double encoding.

Hide the emotify addon

---

plugins/jsconnect/class.jsconnect.plugin.php

Closes https://github.com/vanilla/support/issues/1312
The issue seems to be caused because `entry/jsconnect` was being cached for around 2 minutes, so when then client SSO requested it was returning a nonce that no longer existed. (Nonce is deleted as soon as it's used).
I guess the way of testing this is verifying if `entry/jsconnect` is returning `Cache-Control: no-cache` header. You can try setting up https://github.com/vanilla/stub-sso-providers too and testing against it too.

Add no-cache header to jsconnect

---

plugins/jsconnect/class.jsconnect.plugin.php

Backport: https://github.com/vanilla/addons/pull/771
Issue: https://github.com/vanilla/support/issues/1312

Backport: Add no-cache header to jsconnect

---

plugins/RoleTitle/addon.json

Closes https://github.com/vanilla/support/issues/232
Forces RoleTitle to load after Q&A.

Add priority to Role Title addon

---

plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/js/jsconnect.js

Closes: #776 
This PR will fix looping when trying to log in by passing a flag to the JSConnect JavaScript if it is a Private Community which will not redirect the browser if there is an error.
Also, this PR will add console logging if an Admin has put the JSConnect plugin in Test Mode.
1. Turn on JSConnect, 
2. configure it to be the Defualt method to log in. 
3. Put Forum into Private Community mode. Break your JSConnect authentication provider so that it does not return a `UniqueID`.
4. Try to log in.
5. Observe insane loop.
6. Checkout this branch.
7. Observe an error message when it fails.
1. Configure your JSConnect to be in Test Mode.
2. Observe that when you log in, in the console log there is the Authentication response received.

Fix looping when JSConnect fails and site has Private Community turned on.

---

plugins/CivilTongueEx/Library/ContentFilter.php

Closes https://github.com/vanilla/support/issues/1526
- Find a Youtube link with 'ni' in the url (ex: https://youtu.be/Di11gCVW1nI)
- Make sure your civil tongue addon includes 'ni' as a word to be replaced.
- Post youtube link in comment or discussion
- Observe how it gets filtered.
- Checkout this branch and refresh the page.

Fix Civil Tongue Ex pattern matching boundaries

---

plugins/Signatures/class.signatures.plugin.php

Closes https://github.com/vanilla/support/issues/728
- Enable Signature addon
- Set the maximum number of characters to 5
- Try and update a signature to 0 or 1 characters
- You will get a "Signature is X characters too long" error
- Checkout this branch try again to see the issue resolve
**Further testing:**
- Try the same process above in a different posting format

Fix Signature max length check

---

plugins/TrollManagement/class.trollmanagement.plugin.php

This PR depends on vanilla/vanilla#10284
This partially addresses vanilla/support#1571
It is possible to mark and Admin or Moderator as a troll. This PR adds a permission check before the user is marked as a troll and throws an exception if they have the `Moderation.Manage` permission.

Fix admins can be marked as trolls

---

plugins/Ignore/locale/en.php
plugins/Ignore/views/ignore.php

Complements vanilla/locales#280.
Addresses vanilla/support#1616.
This PR adds translation codes and strings to the ignore plugin.

Add translation codes and strings to ignore plugin

---

plugins/QnA/class.qna.plugin.php

closes https://github.com/vanilla/support/issues/1699
Making an api/v2/discussions call When a Discussion of Type question and QnA Null would fail with this error
```
"message": "Validation Failed",
"status": 422,
"errors": [
{
"field": "status",
"code": "missingField",
"path": "[22].attributes.question",
"status": 422,
"message": "item[22].attributes.question.status is required."
}
]
```
This is happening because of https://github.com/vanilla/addons/blob/master/plugins/QnA/class.qna.plugin.php#L1320
w'ere not setting a default value when that field is null.

Fix discussion API failure when no question status is set

---

plugins/Signatures/class.signatures.plugin.php

The GET endpoint was not working because of an authenticated postback check at the top of the modify endpoint.
Closes https://github.com/vanilla/support/issues/838.

Fix signature  GET API v1 endpoint

---

plugins/jsconnect/class.jsconnect.plugin.php

Depends on vanilla/vanilla#10423
Partially addresses vanilla/support#1618
Closes #788
This PR fixes a problem where jsConnect could be the default authentication provider even when disabled. The jsconnect class now extends SSOAddon rather than Gdn_Plugin, which provides a method to set the `Gdn_UserAuthenticationProvider`'s 'IsDefault' value to 0 for any provider matching the jsConnect 'AuthenticationSchemeAlias'.
1. Set up a jsConnect provider.
1. Set the 'IsDefault' value in the `Gdn_UserAuthenticationProvider` table to 1.
1. Disable the jsConnect addon and verify that the 'IsDefault' value is still 1.
1. Check out this branch.
1. Repeat steps 1-3, except this time verify that the 'IsDefault' value changes to 0.

Fix jsConnect can be default provider when disabled

---

plugins/CloudflareSupport/class.cloudflaresupport.plugin.php

This is currently a warning in our PHP 7.3 build so it would be nice to fix it.

Fix Cloudflare plugin’s loop continue

---

plugins/IPBFormatter/Formats/IPBFormat.php
plugins/IPBFormatter/bootstrap.php
plugins/IPBFormatter/class.ipbformatter.plugin.php

Closes https://github.com/vanilla/support/issues/1562
- Enable the "IPB Formatter" plugin (addons)
- Set the posting format to "BBCode"
- Make a comment and using the editor emoji menu, create a heart emoji
- Put in a line break (press return/enter), make another heart emoji
- Create comment
- the `<br>` line break tag should be escaped (bug)
- Checkout this branch
**Further testing:**
- Make another BBCode comment and add a some BBCode, maybe some acceptable HTML
- Change the format in the DB to "ipb"
- Check if the comment renders alright.

Fix BBCode format when IPB Fomatter is enabled

---

plugins/Spoof/class.spoof.plugin.php

Closes vanilla/support#1869
An admin user is able to spoof in as the system user. This is undesirable because they can then see themes and plugins we may not want them to. This adds a check before displaying the spoof button and prevents it from being displayed for system users.
1. As an admin, go to `dashboard/user`
1. Verify that no system users have spoof buttons.

Fix admins able to spoof system user

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php

Closes vanilla/support#1461
This PR fixes a problem where meta tags aren't being changed by Civil Tongue, resulting in the bad words reappearing when posts are shared via twitter or facebook. This PR replaces appearances of the bad words in meta tags with the chosen replacement.
1. Enable Civil Tongue and set up a forbidden word and its replacement.
1. Make a post with the forbidden word.
1. Using dev tools, look at the meta tags and note that the forbidden words appear in the `content` attribute of meta tags.
1. Check out this branch and verify that the words have been replaced.

Filter meta tags with Civil Tongue

---

plugins/jsconnect/class.jsconnect.plugin.php

This will close vanilla/support#1864
When we do not use JSConnect as the default method of signing in, we have the JSConnect button link directly to the endpoint that creates the JWT to be sent to the Authentication provider. When it is the default method, we don't do that. This causes inconsistencies in the way some customers have coded their applications to handle JSConnect.
This PR will make sure that all the links to sign in pass through the `/entry/jsconnect-redirect` endpoint.
- Configure JSConnect for v3
- Make it the default method for logging in.
- Click to log in, make sure it goes through `/entry/jsconnect-redirect` 
- Turn on private communities, access the site, make sure it goes through `/entry/jsconnect-redirect`
- Make JSConnect **NOT** your default method,  make sure it …

Fix the URL for initiating a JSConnect Sign In when using V3.

---

plugins/QnA/class.qna.plugin.php

Closes https://github.com/vanilla/support/issues/1563
- Make sure you have QnA enabled.
- Go to the Unanswered page and notice the page title is "Recent Discussions"
- Checkout this branch and refresh the page

Fix page title in unanswered page

---

plugins/AuthorSelector/locale/en.php
plugins/NoIndex/locale/en.php

Closes vanilla/support#2035.
This PR adds locale files and translation strings for the NoIndex and Author Selector addons.

Add translation strings for NoIndex and Author Selector addons

---

plugins/ShareThis/class.sharethis.plugin.php

Closes vanilla/vanilla-patches#677
Two parameters that are set by the administrator are not being encoded, making them vulnerable to html injection. This PR runs the strings through the `htmlspecialchars()` method to prevent this.
1. Enable the ShareThis plugin (make sure to set `hidden` to `false` in the plugin's `addon.json`)
1. In the plugin configuration settings, enter `aaaa"><script>alert(1337)</script>` in both the "Publisher Number" and "via Handle" fields.
1. Navigate to a discussion and note that the alert is triggered.
1. Checkout this branch and navigate to a discussion.
1. Verify that the alert is not triggered.

Encode settings strings before outputting them

---

plugins/Sitemaps/class.sitemaps.plugin.php
plugins/Sitemaps/views/settings.twig

closes https://github.com/vanilla/addons/issues/817
**To Test**
- Check the description in the referenced ticket.
- Test the toggle, it should set ['Feature']['discussionSiteMaps']['Enabled']
- Enable private community, check the settings page description.

Add discussionSiteMaps toggle, and fix plugin description

---

plugins/jsconnect/class.jsconnect.plugin.php

This PR will close vanilla/support#2154
This commit https://github.com/vanilla/addons/commit/9f4e3eed21d1438f32a5ac2d307d669de787fe97 wrapped the redirect URL that we use to give users the State token before redirecting them to the authentication provider during JSConnect connections with the `url()` function which added the subfolder where it originated. Unfortunately we pass that URL through the same function later so that sub-communities wind up with double sub-community folders (ie.`https://myformum.com/en/en/entry/jsconnect`).
This PR will fix that.
- Turn on Sub-communities.
- Turn on JSconnect configured for V3
- Configure `$Configuration['Garden']['SignIn']['Popup'] = false;`
- Click Sign In, see that you get redirected to yourdomain.com/subccommunity/subcommunity/entry... which …

Remove the extra subcommunity folder from the JSConnect redirect.

---

plugins/jsconnect/class.jsconnect.plugin.php

This PR will back port vanilla/addons#822
This commit https://github.com/vanilla/addons/commit/9f4e3eed21d1438f32a5ac2d307d669de787fe97 wrapped the redirect URL that we use to give users the State token before redirecting them to the authentication provider during JSConnect connections with the `url()` function which added the subfolder where it originated. Unfortunately we pass that URL through the same function later so that sub-communities wind up with double sub-community folders (ie.`https://myformum.com/en/en/entry/jsconnect`).
This PR will fix that.
- Turn on Sub-communities.
- Turn on JSconnect configured for V3
- Configure `$Configuration['Garden']['SignIn']['Popup'] = false;`
- Click Sign In, see that you get redirected to yourdomain.com/subccommunity/subcommunity/entry... which …

[Backport] Remove the extra subcommunity folder from the JSConnect redirect. 

---

plugins/jsconnect/class.jsconnect.plugin.php

This PR will back port vanilla/addons#822 to 2020.012
This commit https://github.com/vanilla/addons/commit/9f4e3eed21d1438f32a5ac2d307d669de787fe97 wrapped the redirect URL that we use to give users the State token before redirecting them to the authentication provider during JSConnect connections with the `url()` function which added the subfolder where it originated. Unfortunately we pass that URL through the same function later so that sub-communities wind up with double sub-community folders (ie.`https://myformum.com/en/en/entry/jsconnect`).
This PR will fix that.
- Turn on Sub-communities.
- Turn on JSconnect configured for V3
- Configure `$Configuration['Garden']['SignIn']['Popup'] = false;`
- Click Sign In, see that you get redirected to …

[Backport] Remove the extra subcommunity folder from the JSConnect redirect.

---

plugins/Ignore/locale/en.php
plugins/Ignore/views/confirm.php

Closes vanilla/support#2122
This PR fixes a problem where a string in the "Ignore" addon was not getting translated because there was a mismatch between the code in the `t()` call and the code in transifex. This fixes changes the string in the call to match what's in transifex.
1. Enable the "Ignore" plugin.
1. Set the forum language to Italian or French.
1. Ignore someone, then "unignore" them.
1. Note that the unignore text is not translated, but reads "Are you sure you want to unignore {whomever}?"
1. Check out this branch and repeat steps 3 and 4, but note that the text is now translated.

Fix mismatch between unignore translation codes.

---

plugins/Ignore/locale/en.php
plugins/Ignore/views/confirm.php

Closes vanilla/support#2122
This PR fixes a problem where a string in the "Ignore" addon was not getting translated because there was a mismatch between the code in the t() call and the code in transifex. This fixes changes the string in the call to match what's in transifex.
TO TEST
Enable the "Ignore" plugin.
Set the forum language to Italian or French.
Ignore someone, then "unignore" them.
Note that the unignore text is not translated, but reads "Are you sure you want to unignore {whomever}?"
Check out this branch and repeat steps 3 and 4, but note that the text is now translated.

[Backport] Fix mismatch between unignore translation codes.

---

plugins/FeedDiscussions/class.feeddiscussions.plugin.php

Closes vanilla/vanilla-patches#684
Cookies are being sent in the proxy request when an admin adds an RSS feed using the "FeedDiscussions" plugin, which is a security risk. This PR changes the request call so that it does not include cookies.
1. Enable the "Feed Discussions" plugin.
1. Check out this branch
1. Put a breakpoint [here](https://github.com/vanilla/vanilla/blob/1ddcad8a6732f3a24829be5fc395aebafe0a2330/library/core/class.proxyrequest.php#L464).
1. With Xdebug on, add an RSS feed.
1. Verify that the contents of the if-statement are skipped.

Fix cookies leaking when adding feed

---

plugins/Ignore/class.ignore.plugin.php

Closes vanilla/support#2241
Currently, if a user who has been deleted is on another user's ignore list, the ignoring user cannot remove the deleted user from the list. This PR allows deleted users to be removed from ignore lists.
1. As an admin, create a user and ignore the user.
1. Delete the user and view your Ignore list.
1. Note that you now have "[Deleted User]" on your ignore list and cannot unignore them.
1. Check out this branch and try to unignore them again.
1. Note that this time it works.

Allow deleted users to be removed from Ignore list

---

plugins/TrollManagement/class.trollmanagement.plugin.php

related https://github.com/vanilla/support/issues/1086
related https://github.com/vanilla/vanilla-cloud/pull/381

add checks to identify troll users when sending emails

---

plugins/Resolved/class.resolved.plugin.php

Closes https://github.com/vanilla/vanilla-patches/issues/717
- Enable the "Resolved Discussions" addon (not v2).
- Choose a discussiond from your local that can be resolved. Get the discussion ID.
- Comment the following lines:
- https://github.com/vanilla/addons/blob/0ed459ca14a8c764046c2e859cc248044e54b3c4/plugins/Resolved/class.resolved.plugin.php#L129
- https://github.com/vanilla/addons/blob/0ed459ca14a8c764046c2e859cc248044e54b3c4/plugins/Resolved/class.resolved.plugin.php#L133 (the whole block)
(This way, validation is purely based on the transient key)
- As a guest, make a post to resolve the discussion, you can use the code below for the request:
```
(function () {
var endpoint = (new URL(document.location)).origin + …
```

Validate tk on "/resolve" endpoint

---

plugins/TrollManagement/TrollManagementTest.php
plugins/TrollManagement/addon.json
plugins/TrollManagement/class.trollmanagement.plugin.php
plugins/TrollManagement/tests/TrollManagementTest.php
plugins/TrollManagement/views/configuration.php

This is the 'plugin' part for the following issue: https://github.com/vanillaforums/mse/issues/236
As detailed by the following estimate: https://github.com/vanillaforums/estimates/blob/master/mse/mse-troll-plugin-enhancements.md
This is complementary to the following PR: https://github.com/vanilla/vanilla-cloud/pull/2303
**How to test**
- Enable the **Troll management plugin**.
- Configure the plugin.
- Enable fingerprint checks.
- Set a maximum allowed number of user accounts tied to a single fingerprint.
- Logout from the admin account.
- Create a few new user accounts to reach the maximum allowed number of user accounts tied to a single fingerprint.
- Logout & back again as your administrative account.
- Reach the applicants management interface(/dashboard/user/applicants). Your …

Add ban by Fingerprint to the Troll management plugin

---

plugins/TrollManagement/class.trollmanagement.plugin.php
plugins/TrollManagement/views/configuration.php

Closes https://github.com/vanilla/support/issues/4167
This fixes troll management plugin not saving properly because of typos in the settings keys.

Fix typos preventing Troll Management plugin from saving.

---

plugins/TrollManagement/class.trollmanagement.plugin.php
plugins/TrollManagement/views/configuration.php

Backporting #846 to release/2021.008
Related https://github.com/vanilla/support/issues/4167

[Backport 2021.008] Fix typos preventing Troll Management plugin from saving.

---

plugins/TrollManagement/class.trollmanagement.plugin.php

Properties aren't accessed as an array(anymore), but as an object.

Fix the applicants form crash

---

plugins/AuthorSelector/js/authorselector.js

Looks like for authorselector plugin jquery on('contentLoad') event triggers sooner that expected in js file, so changing it to ready() which is equivalent to "DOMContentLoaded" native event.
closes https://github.com/vanilla/support/issues/4516

Fix authorselector.js jQuery load event

---

plugins/TrollManagement/class.trollmanagement.plugin.php

This was flipping back and forth between active and inactive because after being added once, it would be removed in the core declaration, and then added back again on the next structure

Fix the TrollManagement DB structure

---

plugins/ShareThis/addon.json

At request of support a deprecation notice has been added to the plugin ShareThis as it still shows on some staging/test sites but not is available on production.
This closes: https://higherlogic.atlassian.net/browse/APPENG-13922

APPENG-13922: Add deprecation notice to ShareThis Plugin

---

plugins/IPBFormatter/class.ipbformatter.plugin.php

Two functions from the IPBFormatter plugin were triggering this error: 
```Parameter 2 to IPBFormatterPlugin::editorPlugin_getJSDefinitions_handler() expected to be a reference, value given```.
Both functions were expecting the `$args` argument to be a reference. 
See: https://higherlogic.atlassian.net/browse/VNLA-1220
* Use the value rather than the reference in the function signature.
* Set debug mode on
* Enable the `Advanced Editor` plugin and `IPBFormatter` plugin.
* Notice the error message showing up about those two functions.
* Check out this branch, notice the message is gone.
* Set the posting type to IPB.
* Post content in the IPB format.
* Notice that the post is rendered properly.

VNLA-1220 fix/IPBFormatter Warnings by remove reference from function signatures

---

plugins/LinkTypes/js/linktypes.js

This fixes sites that are using the Warn on Leave feature with the LinkTypes plugin as the warn links would not open in a new tab, previously. 
The regex is simple and efficient with an almost impossible chance to get a false positive.
Tested locally on a standard build and using basic embed. Was not able to test on the advanced embed due to CORS errors on two test sites.

VNLA-1083 Fix Link Types working with warn on leave

---

plugins/StopAutoDraft/addon.json
plugins/StopAutoDraft/class.stopautodraft.plugin.php
plugins/StopAutoDraft/tests/StopAutoDraftTest.php

Companion PR to vanilla/vanilla-cloud#5559
This PR changes the logic of the StopAutoDraft plugin to simply set the new `Vanilla.Drafts.Autosave` config value to `false`. This setting is used by the new settings option on the `vanilla/settings/posting` page. Once the config value is set, the addon disables itself. The PR also hides the plugin, so it cannot be found subsequently.

VNLA-1121: Disable StopAutoDraft Plugin Universally

---

plugins/RoleTitle/class.roletitle.plugin.php

Fixes the secondarily reported (but not yet filed) issue in https://higherlogic.atlassian.net/browse/VNLA-8783?focusedCommentId=851182&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-851182
The roletitles plugin is clobbering the session with by adding role strings into it's user object.
I'm gutting that functionality entirely (which was being used apply a css class to the legacy create comment box.
_Side note, this repo hasn't been prettiered so it's the file is also being reformated._

Remove session clobbering from RoleTitle plugin
