plugins/SteamConnect/LICENSE.md
plugins/SteamConnect/class.steam.plugin.php

Fixes licensing info for plugin.

Steam Connect: Change licensing info.

---

plugins/TrollManagement/class.trollmanagement.plugin.php

Add an index to the Fingerprint column in the user table.  The query was taking too long for sites with a large amount of users.

TrollManagement: Add index to user fingerprint.

---

plugins/QnA/class.qna.plugin.php

Fixes potential fatal error when no announcments were present.

QnA: Confirm announcements are a dataset

---

plugins/FileUpload/class.fileupload.plugin.php

As per issue #2345 , Handle EXIF orientation in UploadImage. Must be accompanied by PR #2348, Fix rotation issue with iPhone uploads.

Use SaveImageAs() for images

---

plugins/TrollManagement/class.trollmanagement.plugin.php

Intercept profile user data load to remove ShowCounts for trolls

---

plugins/Pockets/class.pockets.plugin.php

Pockets cannot currently be enabled.

Pockets: fix static calls in setup

---

plugins/TouchIcon/class.touchicon.plugin.php

TouchIcon revisions

---

plugins/Resolved/class.resolved.plugin.php

Blog comments showed as unresolved, and resolving them closed them.

Resolved: de-conflict with blog comments

---

plugins/Spoilers/class.spoilers.plugin.php
plugins/Spoilers/js/spoilers.js

NBBC + Spoilers + BBCode inputformatter required.

Enable spoilers in PMs the rest of the way

---

plugins/FeedDiscussions/class.feeddiscussions.plugin.php

This makes sure the original feed gets credit with a link back.

Adds source to feed

---

plugins/AgeGate/class.agegate.plugin.php
plugins/AgeGate/js/agegate.js
plugins/AgeGate/views/settings.php

Allow underage users to register if they have consent.

AgeGate: Add optional confirmation of consent.

---

plugins/FeedDiscussions/class.feeddiscussions.plugin.php

Tighten permissions to access settings.

Tighten permissions

---

plugins/Example/class.example.plugin.php
plugins/Example/design/example.css
plugins/Example/js/example.js
plugins/Example/views/example.php

Update example plugin coding standards

---

plugins/NBBC/class.nbbc.plugin.php

When size tags had a value for the size that was anything other than a number, the tag would fail to parse.  This PR adds the possibility for PX and EM modifiers to be recognized by the tag, although they are ultimately discarded when determining the size value.

Make size tag parse even when px or em present in NBBC

---

plugins/FeedDiscussions/class.feeddiscussions.plugin.php
plugins/FeedDiscussions/views/feeddiscussions.php

- There is nothing dynamic about the feeds display in the dashboard so
`each` is sufficient.
- Simplify the jQuery a bit.

FeedDiscussions: Replace livequery call

---

archive/cleditor/default.php

https://github.com/vanilla/vanilla/pull/3025

cleditor: Remove livequery

---

plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/js/jsconnect.js

jsConnect: replace livequery

---

plugins/CloudflareSupport/class.cloudflaresupport.plugin.php

Updated and sorted the list of Cloudflare IP's to make a bit more sense and to be easier to scan quickly.

Update Cloudflare IP's

---

plugins/Signatures/class.signatures.plugin.php

Bolsters security on the /profile/signature/modify endpoint.

Signatures: Add permission and postback checks to modify endpoint.

---

plugins/QnA/class.qna.plugin.php
plugins/Resolved/class.resolved.plugin.php

Ensure we have authenticated postbacks in qna, resolve and unresolved endpoints.

QnA and Resolved: Check for authenticated postbacks in endpoints.

---

plugins/Pockets/class.pockets.plugin.php
plugins/Pockets/design/pockets.css
plugins/Pockets/library/class.pocket.php
plugins/Pockets/pockets.js
plugins/Pockets/views/addedit.php
plugins/Pockets/views/delete.php
plugins/Pockets/views/index.php

* Fix bracing.
* Fix casing.
* Fix indents.
* Add docblocks.
* Remove commented code.
* Replace deprecated function usage.
* No functional changes.

Refactor Pockets with current standards

---

plugins/HipChat/LICENSE.md
plugins/HipChat/README.md
plugins/HipChat/class.hipchat.plugin.php

* Basic HipChat notification integration.
* Sends a message to designated room for every new discussion.
I used cURL instead of the HTTP library because the latter is not in 2.2.

HipChat integration 0.1

---

plugins/QnA/class.qna.plugin.php

Lets users accept their own answer.

Allow users to accept their own answer.

---

plugins/Multilingual/class.multilingual.plugin.php
plugins/Multilingual/modules/class.localechoosermodule.php

- Change indentation to 4 spaces.
- Convert method names to camel case.

Update spacing and casing on the multilingual plugin

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/js/QnA.js
plugins/QnA/views/answers.php
plugins/QnA/views/configuration.php

Adds configuration options to the QnA plugin.
Award user points -> On/Off
Points per answers (only for users' first answer to that question) -> uint
Points per accepted answers -> uint

Add points award feature to the QnA plugin.

---

plugins/RoleTitle/class.roletitle.plugin.php

Update the plugin to our standards.
I did not do the comments on purpose because I also need to rewrite the plugin.

Refactor the RoleTitle plugin (Casening)

---

plugins/Multilingual/class.multilingual.plugin.php

Add a third parameter to the setlocale function so that a flag can be tacked on to the end of the redirect on success. Can be useful for triggering javascript and/or messaging.

Add option for redirect when changing locales in Multilingual.

---

plugins/PrefixDiscussionFilter/class.prefixdiscussionfilter.plugin.php

Allow filtering by prefixes.
* Add 2 default filters
* Has prefix
* No prefix
* Generate a list of filters using existing prefixes.

New plugin PrefixDiscussionFilter

---

plugins/RoleTitle/class.roletitle.plugin.php

{Title of this PR} -> Sorry
Fix https://github.com/vanilla/addons/issues/301

Refactor RoleTitle plugin. I should have split this in multiple commit

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php

Relies on https://github.com/vanilla/vanilla/pull/3709

Filter content in conversation message notifications.

---

plugins/Emotify/js/emotify.js

Necessary once this is merged: https://github.com/vanilla/vanilla/pull/3342

Start emotify on contentLoad event rather than 'EditCommentFormLoaded'.

---

plugins/FileUpload/class.fileupload.plugin.php
plugins/FileUpload/class.mediamodel.php

~~Also removes the dependency on the VanillaModel which isn't necessary.~~

Fix notices in the file upload plugin

---

plugins/PrefixDiscussionFilter/class.prefixdiscussionfilter.plugin.php

The constructor of DiscussionsSortFilterModule was not called properly.

Initialize DiscussionsSortFilterModule with the correct parameters

---

plugins/QnA/class.qna.plugin.php

When a discussion is converted to a question, its `QnA` field is never updated to "Unanswered".  This causes the unanswered count to be incorrect, as well as the inability to find that question by its actual "unanswered" status.
This update does the following:
1. Converting a discussion to a question sets the `QnA` field to "Unanswered" by default.  If, for whatever reason, there was an existing field value for `QnA`, it is maintained.
2. Queries for "unanswered" questions have been expanded to include those records with `null` values for their `QnA` field.  This should mean any questions without an explicit `QnA` value set will be included with the "Unanswered" questions.
Closes #344

Fix "unanswered" status for discussions converted to questions

---

plugins/FileUpload/class.fileupload.plugin.php

See https://github.com/vanilla/vanilla/pull/4048

Update Gdn_Media when a discussion is transformed to a comment

---

plugins/BluehostFix/class.phpmailer.php
plugins/NBBC/nbbc/nbbc.php
plugins/NBBC/nbbc/src/nbbc_parse.php

The e modifier was removed from PHP7

Replace preg_replace regexes using the e modifier with preg_replace_callback

---

plugins/welcomepost/class.welcomepost.plugin.php
plugins/welcomepost/design/welcomepost.css
plugins/welcomepost/js/welcomepost.js

Plugins that redirect users to pre-filled discussion that ask them to introduce themselves.

Add welcomepost plugin v1

---

plugins/welcomepost/class.welcomepost.plugin.php

Make the plugin more user friendly since it is an addon now :D

Make the welcomepost plugin create the "welcome" category automatically if needed.

---

plugins/Redirector/class.redirector.plugin.php

Formatting and some code standards

All hail Lord Brackos!

---

plugins/Redirector/class.redirector.plugin.php

Categories, Discussions, Comments, Profiles

Add redirections for lithium community

---

plugins/postnumbering/class.postnumbering.plugin.php

Add indexes "#1" beside posts that link directly to them.
For better result https://github.com/vanilla/vanilla/pull/4203 should be merged too.

Brand new postnumbering plugin!

---

plugins/postnumbering/class.postnumbering.plugin.php

Remove settings from postnumering.

---

plugins/Redirector/class.redirector.plugin.php

Redirect `/archive/index.php?t=1260372.html` properly now!

Add redirection for vBulletin archive urls

---

plugins/welcomepost/js/welcomepost.js

**EDIT: Merge when https://github.com/vanilla/internal/pull/614 is merged**
To merge once https://github.com/kasperisager/vanilla-bootstrap/pull/194 is merged.

Remove the WelcomePost patch about bootstrap3 popups.

---

plugins/FileUpload/class.fileupload.plugin.php
plugins/FileUpload/class.mediamodel.php

Update coding standards in the FileUpload plugin

---

plugins/QnA/class.qna.plugin.php

Add t() to Unanswered Questions title

---

plugins/LastEdited/class.lastedited.plugin.php

Fix log link showing when no log exists

---

plugins/FileUpload/class.fileupload.plugin.php
plugins/FileUpload/js/fileupload.js

Fixes #110
Also adds support for the new(ish) "contentLoaded" event in Javascript.

Restore file upload option to edit comment form

---

plugins/Akismet/class.akismet.plugin.php

Closes #149 
* An invalid key blocks all unverified users from posting, which is a catastrophe.
* Akismet already provides the mechanism for verifying a key, so let's use it.
* Refactor the Akismet builder to allow alternate key testing.

Enhance Akismet to validate your key

---

plugins/Reporting/class.reporting.plugin.php

Fix incorrect highlight route in Community Reporting plugin.

Fix highlight route for Community Reporting

---

plugins/Participated/class.participated.plugin.php

Hide Participated menu for guests

---

plugins/CivilTongueEx/class.civiltongueex.plugin.php
plugins/CssThemes/class.cssthemes.plugin.php
plugins/FeedDiscussions/class.feeddiscussions.plugin.php
plugins/Liked/class.liked.plugin.php
plugins/MathJax/class.mathjax.plugin.php
plugins/Pockets/class.pockets.plugin.php
plugins/PostCount/class.postcount.plugin.php
plugins/RightToLeft/class.righttoleft.plugin.php
plugins/Signatures/class.signatures.plugin.php
plugins/Voting/class.voting.plugin.php
plugins/jsconnect/class.jsconnect.plugin.php

Fixes PostCount functionality + jsConnect menu, among other things.

Remove object pass-by-ref

---

plugins/Pockets/class.pockets.plugin.php
plugins/Pockets/views/index.php

Also don't preview pockets in the dashboard.

Touch up pockets plugin settings page 

---

plugins/CustomizeText/class.customizetext.plugin.php
plugins/CustomizeText/views/customizetext.php
plugins/CustomizeText/views/rebuild.php
plugins/CustomizeText/views/rebuildcomplete.php

Update Customize Text settings for the new dashboard.
Closes https://github.com/vanilla/vanilla/issues/4417

Customize Text settings

---

plugins/Disqus/views/settings.php

Style Disqus settings for the new dashboard.
Closes https://github.com/vanilla/vanilla/issues/4406

Style Disqus settings page

---

plugins/Pockets/class.pockets.plugin.php
plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/views/settings.php

Related: https://github.com/vanilla/internal/pull/647
Closes https://github.com/vanilla/vanilla/issues/4409

Add UsePopupSettings as a key on PluginInfo

---

plugins/Disqus/class.disqus.plugin.php
plugins/Disqus/views/settings.php

Add Disqus to social page and tweak settings.

Tweak Disqus settings

---

plugins/jsconnect/views/settings.php

There is a big difference between a dot and a comma!

Fix jsConnect's help links

---

plugins/Vanoogle/class.vanoogle.plugin.php

Vanoogle plugin class name fix

---

plugins/EmailPasswordSync/class.emailpasswordsync.plugin.php
plugins/FacebookID/class.facebookid.plugin.php
plugins/Voting/class.voting.plugin.php

Replaced that old function!
Fix #318
Replace https://github.com/vanilla/addons/pull/390

Replace ConsolidateArrayValuesByKey by array_column

---

plugins/Voting/class.voting.plugin.php

Fix voting plugin.

---

plugins/jsconnect/class.jsconnect.plugin.php

```php
GetValue($a, $b, $c, true);
```
must be replaced by
```php
val($a, $b, $c);
unset($b[$a]);
```

Unset parameters properly in JsConnect

---

plugins/AgeGate/views/settings.php
plugins/CivilTongueEx/views/index.php
plugins/CustomizeText/views/customizetext.php
plugins/FeedDiscussions/views/feeddiscussions.php
plugins/Pockets/views/addedit.php
plugins/Pockets/views/index.php
plugins/QnA/views/configuration.php
plugins/Reporting/class.reporting.plugin.php
plugins/Reporting/views/settings.php
plugins/ShareThis/views/sharethis.php
plugins/Spoof/views/spoof.php
plugins/TouchIcon/views/touchicon.php
plugins/jsconnect/views/settings.php

Requires https://github.com/vanilla/vanilla/pull/4539

Replace `form-group row` css class with `form-group`

---

plugins/FeedDiscussions/views/feeddiscussions.php
plugins/Pockets/views/index.php
plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/views/settings.php

See https://github.com/vanilla/vanilla/pull/4583

SCSS refactor view edits

---

plugins/jsconnect/functions.jsconnect.php

This make sure that the served request is served as Javascript or JSON and prevent HTML injection.

Set proper content type (Prevent XSS attacks)

---

plugins/Redirector/class.redirector.plugin.php

I have yet to find the correct profile link.

Add Fusetalk categories and threads redirect

---

plugins/Pockets/views/addedit.php

Fixes issue where you can't save/edit a pocket.

Fix pocket form close

---

plugins/Akismet/class.akismet.plugin.php

Introduced by #371
We already have a default server. Do not block builds that don't have it also set in the config.

Fix invalid Akismet server checking

---

plugins/QnA/views/post.php

Fix https://github.com/vanilla/addons/issues/384

Fix empty category text in QnA

---

plugins/Pockets/views/index.php
plugins/Spoof/views/spoof.php
plugins/jsconnect/class.jsconnect.plugin.php
plugins/jsconnect/views/settings.php

Also add section tags around sections.
Relies on https://github.com/vanilla/vanilla/pull/4698/files

Implement header rendering functions

---

plugins/Pockets/views/index.php

Remove extra div in pockets settings page.

Remove extra div in pockets settings

---

plugins/AuthorSelector/class.authorselector.plugin.php
plugins/AuthorSelector/js/authorselector.js
plugins/AuthorSelector/views/changeauthor.php

- Update how Javascript initiates so it doesn't conflict with other addons.
- Spacening, casening, and docs.
- Version to 1.2.

Author Selector: fix Javascript conflict that hides Editor bar in 2.3; update standards

---

plugins/Participated/class.participated.plugin.php

Added a smarty tag in the participated plugin

Add Smarty tag to participated discussions

---

README.md

Let's add this before we get issues about it :)

Addon installation section in README

---

plugins/Spoof/class.spoof.plugin.php
plugins/jsconnect/views/settings.php

Remove js-hijack class.
Relies on https://github.com/vanilla/vanilla/pull/5026

Remove js-hijack class

---

plugins/QnA/class.qna.plugin.php
plugins/QnA/locale/en.php

Add translation for accepted answer activity.
Also remove unneeded locale file, as the strings exist already in site_core.
Needs https://github.com/vanilla/locales/pull/27

Add translation for accepted answer activity.

---

plugins/jsconnect/class.jsconnect.plugin.php

Credits go to [Caylus](https://open.vanillaforums.com/profile/Caylus) who has [found](https://open.vanillaforums.com/discussion/33117/links-to-documentation-not-longer-valid) the old links.

Correct link to documentation and correct some casenings

---

plugins/Sitemaps/README.md

Added missing readme file to plugin.

Sitemap plugin - added readme file

---

plugins/Participated/class.participated.plugin.php

This update is a coding standards overhaul in the Participated plug-in.

Update coding standards in Participated plug-in

---

plugins/Signatures/class.signatures.plugin.php
plugins/Signatures/views/signature.php

Refactored plugin to current coding standard.

Updated Signature plugin to new coding standards

---

plugins/FeedDiscussions/class.feeddiscussions.plugin.php
plugins/FeedDiscussions/js/feeddiscussions.js
plugins/FeedDiscussions/views/feeddiscussions.php

Refactor feeddiscussion to the latests coding standards

---

plugins/Bump/class.bump.plugin.php

Includes fix for links in forums with subfolders

Update coding standards for Bump

---

plugins/Redirector/class.redirector.plugin.php

Can't upload it to open.vanillaforums.com/addon otherwise

Add license to Redirector plugin info

---

plugins/Signatures/class.signatures.plugin.php

#480 introduced a slew of updates to the Signatures addon, including updating some config keys. The problem is the new config keys aren't always being used. For example, [`SignaturesPlugin::checkSignatureLength` checks if a limit is configured by calling `SignaturesPlugin::getMaximumTextLength`](https://github.com/vanilla/addons/blob/7504d0ba53a242678885ce8992d038115d32567f/plugins/Signatures/class.signatures.plugin.php#L239) and then performs comparisons based on the value of the Plugins.Signatures.MaxLength config. The problem is `SignaturesPlugin::getMaximumTextLength` [uses the newer Signatures.Text.MaxLength config](https://github.com/vanilla/addons/blob/7504d0ba53a242678885ce8992d038115d32567f/plugins/Signatures/class.signatures.plugin.php#L791). If these two config values conflict, …

Fix length check in Signatures addon to use new config

---

plugins/Redirector/addon.json
plugins/Redirector/class.redirector.plugin.php

Somehow that plugin still had $PluginInfo.
I updated addon.json and  removed the variable.

Remove $PluginInfo from the redirector plugin

---

plugins/Ignore/class.ignore.plugin.php
plugins/Pockets/class.pockets.plugin.php
plugins/QnA/class.qna.plugin.php
plugins/Spoof/class.spoof.plugin.php
plugins/TrackingCodes/class.trackingcodes.plugin.php
plugins/jsconnect/class.jsconnect.plugin.php

Depends on vanilla/vanilla#5703

Use redirectTo() instead of setting RedirectUrl

---

plugins/Ignore/class.ignore.plugin.php
plugins/Pockets/class.pockets.plugin.php
plugins/Spoof/class.spoof.plugin.php
plugins/TrackingCodes/class.trackingcodes.plugin.php
plugins/jsconnect/class.jsconnect.plugin.php

Depends on https://github.com/vanilla/vanilla/pull/5719

Update setRedirectTo calls to use the $trustedOnly option where necessary

---

plugins/AuthorSelector/class.authorselector.plugin.php
plugins/Bump/class.bump.plugin.php
plugins/FeedDiscussions/class.feeddiscussions.plugin.php
plugins/FileUpload/class.fileupload.plugin.php
plugins/NoIndex/class.noindex.plugin.php
plugins/QnA/class.qna.plugin.php
plugins/Redirector/class.redirector.plugin.php
plugins/Reporting/class.reporting.plugin.php
plugins/Spoof/class.spoof.plugin.php
plugins/TrackingCodes/class.trackingcodes.plugin.php
plugins/Voting/class.voting.plugin.php
plugins/welcomepost/class.welcomepost.plugin.php

Depends on https://github.com/vanilla/vanilla/pull/5713
See the depending task for the description.

Update redirectTo calls to use the $trustedOnly option where necessary

---

plugins/jsconnect/js/jsconnect.js

Allow jsConnect authentication to be called externally
Backport to 2017-Q2-6

Expose JsConnect javascript authentication method

---

plugins/LinkTypes/addon.json
plugins/LinkTypes/class.linktypes.plugin.php
plugins/LinkTypes/js/linktypes.js

https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
Specify rel="noopener noreferrer" when opening external links
I also updated the description of the plugin to highlight that same domain links are not external.

[LinkTypes] Update coding standards and enhance security

---

plugins/QnA/class.qna.plugin.php

Line 819 in the original file was missing an end tag, which could be parsed by some browsers incorrectly. I added the end tag, but also updated the function to make the structure of the its html output clearer.

[QnA] Add missing closing html tag

---

plugins/welcomepost/README.md
plugins/welcomepost/class.welcomepost.plugin.php

Optionally add a default body to the Welcome Post

---

plugins/CloudflareSupport/addon.json
plugins/CloudflareSupport/class.cloudflaresupport.plugin.php

Updates internal IP list for Cloudflare reverse proxy servers.

Update CF ip list

---

plugins/QnA/class.qna.plugin.php

Refactor QnA functions that were missed [The Amazing Casening](https://github.com/vanilla/addons/pull/544) due to the functions using an `include_once` statement. *They include reaction_functions which only defines function.*

Refactor variables case

---

plugins/QnA/class.qna.plugin.php

Fix default tag text for QnA

---

plugins/jsconnect/class.jsconnect.plugin.php

[Backport] Make sure that the target is not empty before setting it

---

plugins/example/class.example.plugin.php

Replaced addSideMenu(), $sender->Statusmessageand and getView()
Use dashboardNavModule_init_handler instead of base_getAppSettingsMenuItems_handler
Rename plugins config keys to "example.*" instead of "Plugin.Example.*"

Replace deprecated calls and include some current best practices

---

plugins/categoryaslink/addon.json
plugins/categoryaslink/class.categoryaslink.plugin.php

Use a category on the categories page as a link to another category or discussion.

---

plugins/Signatures/views/signature.php

Depends on https://github.com/vanilla/vanilla/pull/6453

Add image upload to Signatures

---

plugins/QnA/class.qna.plugin.php

Depends on https://github.com/vanilla/internal/pull/1474

Add QnA record type to the search API

---

plugins/Liked/class.liked.plugin.php

This update addresses a potential issue with the Liked addon, where the generated markup can be malformed.

Fix potential for broken markup generated by Liked addon

---

plugins/HipChat/class.hipchat.plugin.php

Backport: Fix HipChat comment author data

---

plugins/HipChat/class.hipchat.plugin.php

Backport: Fix logic inversion in HipChat addon

---

plugins/AuthorSelector/class.authorselector.plugin.php

Backport #617 which closed https://github.com/vanilla/addons/issues/615

[Backport] Fix double url() call

---

plugins/Bump/class.bump.plugin.php

closes #631 
Double URL call causing a problem with Sub-communities when a discussion is bumped.

Bump: Double url() call 

---

plugins/Bump/class.bump.plugin.php

Backport: Bump: Double url() call

---

plugins/Akismet/class.akismet.plugin.php

Closes #651
All the necessary information as to why this change was made should be in the issue.

Fix akismet overwriting another plugin spam detection

---

plugins/QnA/class.qna.plugin.php

Backport: calling redirectTo with trustedonly set to false (2.7)

---

plugins/AuthorSelector/addon.json
plugins/CivilTongueEx/addon.json
plugins/FeedDiscussions/addon.json
plugins/FileUpload/addon.json
plugins/ForumMerge/addon.json
plugins/Ignore/addon.json
plugins/LastEdited/addon.json
plugins/MathJax/LICENSE.md
plugins/MathJax/addon.json
plugins/Multilingual/addon.json
plugins/NBBC/addon.json
plugins/QnA/addon.json
plugins/Redirector/addon.json
plugins/RoleTitle/addon.json
plugins/ShareThis/addon.json
plugins/Sitemaps/addon.json
plugins/Spoof/addon.json
plugins/debugbar/LICENSE.md
plugins/debugbar/addon.json
plugins/jsconnect/addon.json
plugins/necro/addon.json

These changes reflect what I released on the open source directory for these addons on Sunday, Feb 10. It consists of version bumps, license additions, and min requirement increases (usually to 2.5 to be safe).

Update licenses and versions for open source release

---

plugins/Participated/ParticipatedCounterProvider.php
plugins/Participated/class.participated.plugin.php

Add ParticipatedCounterProvider to Participated plugin 
Relates to: https://github.com/vanilla/vanilla/pull/8579

Add ParticipatedCounterProvider

---

plugins/QnA/class.qna.plugin.php

Backport: Qna Fix Error Posting Questions (2019.005)

---

plugins/QnA/class.qna.plugin.php

Changes made here https://github.com/vanilla/addons/pull/701 appear to have broken posting discussions.
closes Vanilla/support#331

Fix Qna overriding post creation

---

plugins/QnA/class.qna.plugin.php

Backport: Fix Qna overriding post creation (2019.005)

---

plugins/FeedDiscussions/class.feeddiscussions.plugin.php

This PR is to backport a security patch to Addons.

Backport: Add permission check when deleting a feed.

---

plugins/welcomepost/class.welcomepost.plugin.php

Since all entry forms are AJAX forms now redirects need to be changed to `Gdn_Controller::setRedirectTo()`.

Fix redirect in the welcome post

---

plugins/jsconnect/class.jsconnect.plugin.php

Update hash comparison method in jsConnect.
Closes vanilla/vanilla-patches#558

Fix comparison condition for critical data when compare hashes.

---

plugins/QnA/class.qna.plugin.php

Merges master from vanilla/addons-patches

Sync addons-patches

---

plugins/ForumMerge/class.forummerge.plugin.php

Validate form value 'Database',
other form values sanitized through PDO->prepare when query
Closes: https://github.com/vanilla/vanilla-patches/issues/423

Fix database name validation in Forum Merge addon

---

.circleci/config.yml

Enable circleCI build and tests
Relates to: https://github.com/vanilla/internal/issues/1921

Enable circleCI build and tests

---

plugins/QnA/tests/Sphinx/SearchQuestionTest.php

Update test dependency: + advancedsearch

Fix test for release

---

plugins/QnA/models/SearchRecordTypeAnswer.php
plugins/QnA/models/SearchRecordTypeQuestion.php

Relates to: https://github.com/vanilla/vanilla/pull/9400

Add infrastructure template to SearchRecordType models in QnA plugin

---

plugins/welcomepost/class.welcomepost.plugin.php

This PR fixes https://github.com/vanilla/support/issues/532
The WelcomePost Addon was created to detect if a user was connecting to a forum for the first time and, if so, redirecting them to prompt them to post a "Welcome" discussion in a "Welcome" category. For some time this has stopped redirecting. This arises because the plugin was using the SetRedirect method which gets over-written later on the EntryController. 
This PR will set the Target in the form. Small improvements introduced in this PR is doing multiple checks to see if the user hadn't created his account by another SSO method, to avoid sending a user to the Welcome Post page after logging in using a different provider. 
- Turn on the plugin.
- Make sure you have a category with the URL 'welcome'.
- Create a user through the …

Fix users not being redirected to the Welcome Post page in the WelcomePost Addon.

---

plugins/Multilingual/addon.json
plugins/Multilingual/class.multilingual.plugin.php

Closes https://github.com/vanilla/addons/issues/228.

Fix casing of multi-byte locale display names in Multilingual

---

plugins/jsconnect/class.jsconnect.plugin.php

Closes #774.
This PR changes the log level for the 'jsconnect_success' event to INFO.

Change log level for jsconnect_success event to INFO from ERROR

---

plugins/QnA/openapi/qna.yml

Depends on https://github.com/vanilla/vanilla/pull/10713.
Closes https://github.com/vanilla/addons/issues/700.

Add Q&A’s expand parameters to the discussions endpoints

---

plugins/QnA/class.qna.plugin.php

Closes https://github.com/vanilla/addons/issues/816

Add  QnA meta tag to discussion

---

plugins/jsconnect/class.jsconnect.plugin.php

This PR aims to alleviate an issue with private communities where resources requested from connect pages served through the framework can cause multiple overlapping SSO tokens to cause issues with requests.

Allow jsConnect to re-use SSO tokens

---

plugins/CloudflareSupport/class.cloudflaresupport.plugin.php

There was another continue triggering a warning.

Fix Cloudflare’s continue

---

plugins/QnA/src/scripts/entries/common.tsx

Add QnA support to new search

---

plugins/TrollManagement/class.trollmanagement.plugin.php

related https://github.com/vanilla/vanilla-cloud/pull/1558

Fix checking for troll users before comment save event

---

plugins/TrollManagement/class.trollmanagement.plugin.php

Backport. https://github.com/vanilla/addons/pull/848

Backport PR 848 to 2021.008

---

plugins/TrollManagement/class.trollmanagement.plugin.php

Backporting #848 to release/2021.009
Related to https://github.com/vanillaforums/mse/issues/236#issuecomment-832748827

Backport PR 848 to 2021.009

---

plugins/TrollManagement/class.trollmanagement.plugin.php

Backporting #855 to release/2021.016

[Backport 2021.016] Fix the TrollManagement DB structure

---

plugins/TrollManagement/class.trollmanagement.plugin.php

Applied PR 3504 (https://github.com/vanilla/vanilla-cloud/pull/3504) to release 2021.017.
Related to the following issue: https://github.com/vanilla/addons/pull/854

Backported PR 3504 changes to release 2021.017

---

plugins/RoleTitle/class.roletitle.plugin.php

Closing issue [VNLA-519](https://higherlogic.atlassian.net/browse/VNLA-519)
Replication Steps
Activated plugin Role Title and Private Discussions
Browsed as guest in incognito window
Clicked random discussion title(s)
Saw error page
Debug revealed issue to be with Role title plugin

FIX/ Correcting error when comments are not pulled.

---

plugins/Liked/addon.json

Requested by technical writers - corrects brand name to proper case - Facebook

APPENG-16421: updates language used in Liked addon

---

plugins/IPBFormatter/Formats/IPBFormat.php

The IPBFormatter plugin is causing 500.
* Bring `renderHtml` and `renderQuote` in line with the parent function. Bring in the optimization that were made as well.
* Prettier.
* Enable the plugin. 
* Notice that any page returns a 500.
* Checkout this branch.
* Notice that the site now properly loads.

VNLA-3426: Fix IPBFormatter 500 by updating function signature

---

plugins/IPBFormatter/Formats/IPBFormat.php

Backporting #873 to release/2023.002

[Backport 2023.002] VNLA-3426: Fix IPBFormatter 500 by updating function signature
